### ISSUE TITLE
ALC269VC_v3 for Lenovo ThinkPad L530

### ISSUE THREAD

**Issue by johnstray** [insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12#1]
I reverted to the Vanilla AppleHDA in S/L/E so that I could try this method of patching.

Unfortunately, the sound devices fail to show up in System Preferences > Sound > Output/Input, however, they do show under System Information > Audio > "Intel High Definition Audio"

I still have the same DSDT that you provided earlier over at OSXLatitude forum.
I dropped cloverHDA.kext into EFI/EFI/CLOVER/kexts/10.10, 10.11 & 10.12.
I switched out the config.plist to the one included in the ZIP from here, but added the option to it to load kexts as this was missing from it.

**Comment by insanelydeepak** [comment]
Hello this kext is meant to use in S/L/E, so please install it 
Make sure you have applied clover patches from cloverHDA.plist to your plist 
as you mentioned you did already

**Comment by johnstray** [comment]
Tried installing into S/L/E, but still no luck. This time no devices showed under Intel HDA in Sys Info

**Comment by johnstray** [comment]
Tried the update in commit "1382dc11ba65146339db00934bb95e54d7fa4788". Unfortunately, it did not work. Same results as my last comment.

**Comment by insanelydeepak** [comment]
are you sure have applied Clover patches ? , bocz AppleALC and Patched AppleHDA  is working , this is also same except have to apply Clover patches

**Comment by johnstray** [comment]
I used the clover config.plist patches that were included in the zip from here, and also temporarily disabled the hdmi port fix ones from the AppleHDA tests so that only patches in that zip were used. I'm still using the same dsdt that you had given on the forum.

**Comment by insanelydeepak** [comment]
what OSX Version you are trying it ?

**Comment by johnstray** [comment]
10.11.6

**Comment by insanelydeepak** [comment]
can you try this 

[ALC269VC_v3.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/517594/ALC269VC_v3.zip)

**Comment by johnstray** [comment]
Just out to dinner with family at the moment. I'll give him a try in about 2 hours.

**Comment by johnstray** [comment]
That one worked perfectly. Internal, external and HDMI all worked.

**Comment by insanelydeepak** [comment]
👍 
this repo is only for 10.12 Mac OS Sierra , we were testing on 10.11 El Capitan , that's why nothing was working , now I updated CloverHDA repo with your codec 

Thanks

**Comment by chuckhacker** [comment]
I'm using the ALC269VC_v3 from master, and I can only hear sound when my headphones are plugged in. The speakers do not play any sound when there are no headphones plugged in, even with the volume turned up all the way to the right. Any ideas? I am using layout ID 13.

**Comment by insanelydeepak** [comment]
use EAPDFix or Codec_commander

**Comment by johnstray** [comment]
@insanelydeepak : Can you jump on the OSXLattitude forum? I sent you a PM on there quite a while ago, but you didn't respond.

**Comment by insanelydeepak** [comment]
Ok 
check you PM Box

**Comment by insanelydeepak** [comment]
@mgraham you should post troubleshoot file

**Comment by mgraham** [comment]
@insanelydeepak - thank you - I figured out what was going on - there was something in my DSDT.aml that was preventing the audio drivers from working.  Someone helped me by rebuilding my DSDT.aml from scratch and that suddenly made the audio start working.

**Comment by insanelydeepak** [comment]
enjoy good sound :)
