### ISSUE TITLE
Support for ALC299

### ISSUE THREAD

**Issue by silent3rror** [insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12#10]
Need support for 0x10ec0299
`Codec: Realtek Generic
Address: 0
AFG Function Id: 0x1 (unsol 1)
Vendor Id: 0x10ec0299`

**Comment by insanelydeepak** [comment]
codec_dump is required

**Comment by insanelydeepak** [comment]
I assume you are not available to fix this issue 
for now I'm closing issue 
feel free to re-open issue 

Regards 
Deepak

**Comment by dcshoes23** [comment]
Hi, I have this one as well, here is the codec dump:
[card0-codec#0.txt](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/1763564/card0-codec.0.txt)

**Comment by insanelydeepak** [comment]
Hi 
OSX Version ?

**Comment by dcshoes23** [comment]
The latest High Sierra

**Comment by dcshoes23** [comment]
10.13.3
