### ISSUE TITLE
ALC298 Kabylake Chipset : Device recognized No Audio

### ISSUE THREAD

**Issue by buhlaze** [insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12#12]
I have the NEW Dell XPS 15 (9560) I followed the instructions completely (CloverHDA in S/L/E folder, patches in Config, Layout 13 in Config, vanilla AppleHDA in S/L/E for alc298). The Devices show up but no sound comes out. This is the same rather i use AppleALC or CloverHDA. What can I do to get the sound to work? I am on 10.12.5. VoodooHDA works completely fine, but i want to keep my system as vanilla as possible. Layout I use is 13 and this laptop is suppose to use alc3266 which i believe is basically alc298.

**Comment by insanelydeepak** [comment]
is it having a KabyLake chipset ?

**Comment by buhlaze** [comment]
yes its kabylake

**Comment by insanelydeepak** [comment]
Hi 
you should read this 
https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/issues/11#issuecomment-303970182

already having trouble with Kabylake chips

**Comment by buhlaze** [comment]
That didn't work. Is this a problem that ALL kabyLake notebooks are having?

**Comment by insanelydeepak** [comment]
Hi 
Closing it here and one issue is to enough to fix 298 

Thanks
