### ISSUE TITLE
Alc3266/298 for Alienware 15R3

### ISSUE THREAD

**Issue by MacMerc** [insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12#16]
Using CloverHDA and Injecting 13 and HDAS to HDEF Clover patch
-I get Audio Menu bar loaded (not greyed out)
-Working volume keys
-Jack sense (auto switches to headphones)
-Working Microphone!

But.  Audio playback NOT working.  No sound.  Any playback instantly start/stops.

So, it's very close, but needs pathmaps corrected.  Could you kindly take a look?

[Linux_Codec_Dump ALW15R3_ALC3266.txt](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/1032897/Linux_Codec_Dump.ALW15R3_ALC3266.txt)
[codecgraph outputs.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/1032911/codecgraph.outputs.zip)

**Comment by K0guma** [comment]
Seems like ok dell laptop has it. Is it kabylake?

**Comment by K0guma** [comment]
*all

**Comment by MacMerc** [comment]
Laptop is Alienware 15 R3, with i7-7700HQ cpu, so Kabylake CPU.  But when I run Toleda script for 200 series motherboard it says it's not kabylake motherboard.

**Comment by insanelydeepak** [comment]
try this 

sudo perl -pi -e 's|\x3d\x70\xa1|\x3d\xf0\xa2|g' /System/Library/Extensions/AppleHDA.kext/Contents/Plugins/AppleHDAController.kext/Contents/MacOS/AppleHDAController

**Comment by insanelydeepak** [comment]
Kabylake Chipset is not supported now , you have to wait till OSX next update , otherwise you have to use QuickFix are available 
I don't kabylake hardware so can't exactly patch is working or not :(

**Comment by insanelydeepak** [comment]
#

**Comment by MacMerc** [comment]
Copied and pasted, rebuilt kextcache with Kext Utility, rebooted.  no luck so far, same situation.  I have CloverHDA installed, and Codec Commander, and was vanilla AppleHDA 10.12.5.
![screen shot 2017-05-26 at 3 24 05 pm](https://cloud.githubusercontent.com/assets/26944182/26516765/7bdb88b4-4227-11e7-8378-22e65fe8a6a3.png)

**Comment by insanelydeepak** [comment]
can you try AppleALC ?? use layout 13 , it has same resources

**Comment by MacMerc** [comment]
Strange thing is that Mic input works, so it seems like pathmaps need to be adjusted for this chipset.  I'm using cloverHDA from the Alc298 that is posted in this forum

**Comment by MacMerc** [comment]
ok gimme a sec to try it

**Comment by insanelydeepak** [comment]
I see 
mic is really working ?? confirm it was working before patch or with patch

**Comment by MacMerc** [comment]
Mic was working before terminal patch with ALC298 CloverHDA.kext, and layout 13 and HDAS to HDEF Clover patch.  Using vanilla AppleHDA kext.  I now just tried to remove CloverHDA and install latest vit9696 AppleALC kext but no device detected now.

**Comment by insanelydeepak** [comment]
ok I will look at codec_dump and try to fix it

**Comment by buhlaze** [comment]
I'm still havin the same problem, as i'm using the Dell Xps 15 (9560) with kaby lake.... So, it does seem liek a problem with the dell kaby lakes. I to, feel like its all about fixing the paths. I'm having the similar problem as u with only the mic working. I have devices showing up, but no sound coming out. I'm studying pathmaps as i'm not real good in that area, hope to get a solution soon rather its through me or so m eone else to get on this hump for all dell's with kaby lake.

**Comment by insanelydeepak** [comment]
yes dell always has big difference between their codecs like Skylake , now Kabylake 
dont worry will look and report

**Comment by insanelydeepak** [comment]
try this 

[298.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/1033948/298.zip)

**Comment by buhlaze** [comment]
This fix that worked for e was upgrading to the newest RehabMan-FakePCIID-2017-0527.zip

**Comment by K0guma** [comment]
I asked rehabman to update it. Should work fine.

**Comment by insanelydeepak** [comment]
so using New FakePCIID fixes sound issue in Kabylake Laptops

**Comment by insanelydeepak** [comment]
issue should be close now

**Comment by MacMerc** [comment]
Sorry I was away few days for holiday.  The 298.zip link above does not work for me.  So I'm still using same CloverHDA as before.  
I just now updated to latest FakePCIID and no changes to my sound.  Mic still works, but no audio from speakers.  Isn't my issue still having not latest changes to pin config?

**Comment by MacMerc** [comment]
@ buhlaze -- which kext did you use?  Although I don't think it matters because I have Alienware with 3266/298  not xps.  
@ K0guma -- how does updated FakePCIID help with my path maps problem?
@ Insanelydeepak -- thanks very much for your help, I cannot understand how to fix pathmaps.  Can you please repost the 298.zip that you were asking me to try?  Sorry I did not try it in time before link expired.

**Comment by MacMerc** [comment]
Update!  I installed both 5/27/17 FakePCIID.kext and FakePCIID_Intel_HDMI_Audio.kext  (I also have cloverHDA installed, and layout 3, and codec commander.)
Internal Mic still works.

Sound from speakers works!

Headphone sound plays but it is garbled and distorted.  Also iPhone headphone plug (with integrated mic) do not work.  Only normal stereo headphone plug.

Jack sense works, but again it's bad audio from headphones.

Hdmi audio does not work.

I don't know if fake hdmi kext is doing anything, perhaps it's because I rebuilt cache again but it's nice to have speakers working.  Can you help fix the headphone jack issue?

**Comment by insanelydeepak** [comment]
use alcfix from above post

**Comment by insanelydeepak** [comment]
> - thanks very much for your help, I cannot understand how to fix pathmaps. Can you please repost the 298.zip that you were asking me to try? Sorry I did not try it in time before link expired.

did you tried all above kexts I posted ?

**Comment by MacMerc** [comment]
That link goes 404,, I cannot download.

**Comment by insanelydeepak** [comment]
> That link goes 404,, I cannot download.I could not try kexts because link not working.

I will try to make another soon

**Comment by insanelydeepak** [comment]
try this 
[ALC298 AlienWare.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/1050120/ALC298.AlienWare.zip)

**Comment by MacMerc** [comment]
You are amazing.  Headphone sound is now clear and it switches instantly when I plug or unplug.  So, to summarize for future readers.

Using AppleHDA ALC298 Alienware from above link.  Injecting layout-id 13 and using HDAS to HDEF Clover patch
Install ALC_fix by going to terminal, cd to folder, type ./install.sh  (this will copy items to right places)
Install above listed AppleHDA with Kext Utility or EasyKextPro (so it rebuilds caches), and reboot.

-Speakers work
-Headphones work
-Jack sense works (auto switches to headphones and back)
-Internal Microphone works
-Audio after sleep works

(if a triple plug headphone (with integrated mic) is plugged in, the stereo works great, but headphone mic is not detected.)

Now I'm off to see about getting HDMI audio from the integrated 1070.  Thanks very much!

**Comment by insanelydeepak** [comment]
can you check your external Mic is working 

> Now I'm off to see about getting HDMI audio from the integrated 1070
not getting you

**Comment by MacMerc** [comment]
By Internal Mic i'm talking about the Mic built into the bezel/webcam of display.  Yes this works!

By external Mic, are you talking about headphone/mic plugged into headphone port?  No this is not working.

Also, HDMI audio is a separate issue?

**Comment by insanelydeepak** [comment]
> Also, HDMI audio is a separate issue?

you need Framebuffer patch as per your GPU ..

let me try fix external Mic

**Comment by MacMerc** [comment]
I discovered big mistake today.  Internal Mic is not actually working with your patched kext.

I made a mistake and found leftover "aDummyHDA.kext " in /S/L/E from previous method.  If I remove this kext the internal mic stops working!

So, your patched "ALC298 Alienware" makes speaker and headphone work perfectly.  But not any mics.
If I also install "aDummyHDA.kext" the internal mic begins to work.  Both kexts together gives me all 3 internal devices working, but still no external mic.

I've attached the kext for you to look at.  Perhaps the changes can be integrated into your patched "ALC298 Alienware" kext.
[aDummyHDA.kext.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/1065323/aDummyHDA.kext.zip)

**Comment by insanelydeepak** [comment]
> I discovered big mistake today 

this is strange 
what layoutID you have ?

**Comment by MacMerc** [comment]
Layout id 13
![screen shot 2017-06-10 at 12 04 59 pm](https://user-images.githubusercontent.com/26944182/27006641-1b8cbe24-4dd5-11e7-92b7-201e34d3b947.png)

**Comment by insanelydeepak** [comment]
remove dummy kext and Re-build caches use EasyKextPro

**Comment by MacMerc** [comment]
yes I've already done that and produced the result stated above.  But I will test again.

**Comment by MacMerc** [comment]
Ok, just tested and confirm that if I remove aDummyHDA I lose mic input.  The device still shows up, but no sound comes in.
This is very strange.  I'm actually using a combination of kexts to make this work.
CloverHDA.kext (from your 298, in the repository).
FakePCIID_Intel_HDMI_Audio.kext
CodecCommander.kext
and your patched AppleHDA.kext

All together it works.  
But If I remove FakePCIID_Intel_HDMI_Audio.kext my sound stops working too.

Any ideas?

**Comment by insanelydeepak** [comment]
remove CloverHDA , use only patchedAppleHDA provided by me 
remove aDummyHDA 
remove this one too  remove FakePCIID_Intel_HDMI_Audio.kext
use latest FakePCIID kext from rehabman 

then report , so we can have better understanding

**Comment by MacMerc** [comment]
Update!  Ok, I removed CloverHDA and aDummyHDA.

You are correct.  Mic is now working without the aDummyHDA

**Comment by MacMerc** [comment]
Ok, one more update!  I cannot remove FakePCIID_Intel_HDMI_Audio.kext

If I remove it my audio devices show up,, BUT any playback instantly stops, and there's no sound.

**Comment by insanelydeepak** [comment]
use https://bitbucket.org/RehabMan/os-x-fake-pci-id/downloads/

**Comment by MacMerc** [comment]
Yes, I'm already using the 05/27 build

**Comment by insanelydeepak** [comment]
now what's issue ?? external Mic ?

**Comment by MacMerc** [comment]
Yes, external mic doesn't work.

**Comment by MacMerc** [comment]
Have you had any success fixing external mic on Alc 3266/298?

**Comment by insanelydeepak** [comment]
Thanks for reminder I forgot 
can you post kext wich working best for you and codec_dump too ?

**Comment by MacMerc** [comment]
Ok, here you go.  I include both Linux codec dump, and codec graph method.
[kext and codec dump.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/1099382/kext.and.codec.dump.zip)

**Comment by insanelydeepak** [comment]
Try this 

[AppleHDA-279.48-ALC298.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/1099469/AppleHDA-279.48-ALC298.zip)

**Comment by MacMerc** [comment]
The result is same as before.  External mic still not working.

**Comment by insanelydeepak** [comment]
try this 

one question :  external Mic detects ?

[alc298.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/1108570/alc298.zip)

**Comment by MacMerc** [comment]
I tried all 3 kexts but external mic doesn't detect.

So that's the problem so far.  When I plug in there is no detection of external mic.

**Comment by MacMerc** [comment]
Any ideas on how we can make the external mic detect on Alienware 15r3?

**Comment by insanelydeepak** [comment]
you need codec commander with custom profile

**Comment by insanelydeepak** [comment]
are you using ALCFix ??

**Comment by MacMerc** [comment]
Yes I'm using ALCFix.  Headphone detects but external Mic doesn't.

**Comment by insanelydeepak** [comment]
using codec_commander ??

**Comment by insanelydeepak** [comment]
use SSDT and add it to clover sorted list 

[ALC298.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/1167831/ALC298.zip)

**Comment by MacMerc** [comment]
Yep I'm using Codec Commander.  I put the SSDT in Clover > ACPI > Patched, and added it to sorted order.  But it still doesn't detect external mic.  Both ALC fixes in the last post broke my headphone sound so I went back to an old one.  
Not sure why this one is so difficult, but I'm very happy to have everything else working anyway, and I'll just use internal mic.  Thanks again for your help.

**Comment by insanelydeepak** [comment]
Hi 
can you post best working kext (any other files too ) for you ? 
I will add it to ALC298 Alienware , so many people are looking will get it

**Comment by insanelydeepak** [comment]
> Not sure why this one is so difficult, but I'm very happy to have everything else working anyway, and I'll just use internal mic. Thanks again for your help.

recently I fixed ALC292 same you have issue , it took time to make all input/output now its perfect working

**Comment by MacMerc** [comment]
Ok here are complete instructions and files that work.
1) Be sure to use latest FakePCIID kexts including FakePCIID_Intel_HDMI_Audio.kext.
2) download and install Codec Commander kext
3) download and install ALC298 Alienware package.  Install - a) AppleHDA.kext. b) run the AlcFix.
[ALC298 AlienWare.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/1191902/ALC298.AlienWare.zip)

**Comment by insanelydeepak** [comment]
Thanks
