### ISSUE TITLE
Not Working On Dell XPS 13 9350

### ISSUE THREAD

**Issue by maxexcloo** [insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12#2]
Using ALC256 ZIP file, I cannot get cloverHDA to load...
I have tried injecting the KEXT and also installing it to /S/L/E/ but no dice, have applied the DSDT patch and all your included config.plist patches.

Files are attached, thank you for your help 👍 

![system information](https://cloud.githubusercontent.com/assets/927210/19335111/6a422068-914c-11e6-85be-2fdfb33f3902.png)
[kextstat.txt](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/526065/kextstat.txt)
[IOregistery.ioreg.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/526068/IOregistery.ioreg.zip)
[config.plist.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/526069/config.plist.zip)
[DSDT.dsl.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/526073/DSDT.dsl.zip)
[CLOVER.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/526074/CLOVER.zip)

**Comment by maxexcloo** [comment]
Also, why is it that you shouldn't inject this KEXT via Clover? I'm just curious as I like to keep my macOS partition at stock if I can :)

**Comment by insanelydeepak** [comment]
try this DSDT 
[DSDT.aml.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/526193/DSDT.aml.zip)

> Also, why is it that you shouldn't inject this KEXT via Clover? I'm just curious as I like to keep my macOS partition at stock if I can :)

you should use AppleALC , use it from Clover Kext 
https://www.dropbox.com/s/4nbcmqd7qkjlvnt/AppelALC%20v1.0.17.zip?dl=0

**Comment by maxexcloo** [comment]
`try this DSDT 
DSDT.aml.zip`

Could you tell me what changed? I am writing a guide and this would help me help others!

`you should use AppleALC , use it from Clover Kext`
With AppleALC do I put cloverHDA and AppleALC into the KEXT directory? Is that the only change (as opposed to no AppleALC and cloverHDA in the /S/L/E/ directory?

Thank you!

**Comment by maxexcloo** [comment]
I removed CodecCommander.kext and cloverHDA.kext from the /S/L/E/ folder and booted with caches disabled using your new DSDT.aml and cloverHDA.kext, AppleALC.kext and CodecCommander.kext in the KEXTs directory in Clover, still nothing coming up in the Output & Input panels of the Sound preferences sadly, am I doing everything right?

**Comment by insanelydeepak** [comment]
> Could you tell me what changed? I am writing a guide and this would help me help others!

sure will let you know when confirm its working for you 



> With AppleALC do I put cloverHDA and AppleALC into the KEXT directory? Is that the only change (as opposed to no AppleALC and cloverHDA in the /S/L/E/ directory?

just use AppleALC , remove CloverHDA and clover patches from config.plist

**Comment by maxexcloo** [comment]
Ah, will try that now!

**Comment by maxexcloo** [comment]
Removed all AppleHDA entries from KextsToPatch and removed cloverHDA.kext from Clover, booted in no cache mode, no entries still, do I need CodecCommander.kext or should I also remove that?

I really appreciate your time :)

**Comment by insanelydeepak** [comment]
can you check kextstat  now and show screenshot of about myMac audio

**Comment by insanelydeepak** [comment]
>  do I need CodecCommander.kext or should I also remove that?

remove for now ,will use in after you get audio enabled

**Comment by maxexcloo** [comment]
Sorry about the quality, on my iPad right now!

**Comment by insanelydeepak** [comment]
hello , is issue fixed ?

**Comment by maxexcloo** [comment]
I couldn't fix it with this kext but I got another working in my guide!
https://www.tonymacx86.com/threads/guide-dell-xps-13-9350-sierra.204730/

**Comment by insanelydeepak** [comment]
we have to find out why it's not working for you , may be kext wasn't loading ..
it working fine for user I patched and may be I can tweak it for you too 

let it you have working Audio going to close this issue 
Good Luck 👍  Enjoy Native Sound :)

**Comment by maxexcloo** [comment]
What is the difference between AppleHDA, cloverHDA and other solutions? I wish to use the best solution! Currently AppleHDA_ALC256.kext is working for me but I don't know the source of this KEXT and do not trust it as such...

**Comment by insanelydeepak** [comment]
can you try this one ? 
[ALC256.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/537915/ALC256.zip)

**Comment by insanelydeepak** [comment]
> What is the difference between AppleHDA, cloverHDA and other solutions? 
CloverHDA and kext you are using is Same method cloverMethod 

>  I wish to use the best solution! Currently
best solution now is AppleALC , no need to install anything 

can you test above version cuz i found something was missing

**Comment by maxexcloo** [comment]
I removed AppleHDA_ALC256.kext from /System/Library/Extensions/ and installed the cloverHDA.kext you just linked using Kext Utility, audio isn't working anymore on reboot :(
If you go here you can see all my settings and download my CLOVER directory:
https://www.tonymacx86.com/threads/guide-dell-xps-13-9350-sierra.204730/

**Comment by insanelydeepak** [comment]
this one 

[ALC256.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/537959/ALC256.zip)

using layout 13 ??

**Comment by insanelydeepak** [comment]
provide kextstat Output too

**Comment by maxexcloo** [comment]
I just realised I wasn't injecting layout 13 (having reverted after last try), I'm trying layout 13 with the KEXT you linked here:
https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/issues/2#issuecomment-254704777

The system boots fine, audio comes up but no sound will come out of the speakers, odd.

**Comment by insanelydeepak** [comment]
using Codec_commander ?? can you try without it ?

**Comment by maxexcloo** [comment]
I removed CodecCommander, still no dice...

**Comment by maxexcloo** [comment]
Headphone microphone & audio also does not work sadly :(

**Comment by insanelydeepak** [comment]
try this one 

[ALC256.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/538006/ALC256.zip)

i need codec_dump to make specific verison according your system

**Comment by maxexcloo** [comment]
How can I do a codec_dump? I'll run one!

**Comment by maxexcloo** [comment]
That version works! Headphones still do not however... If you'd like I can codec_dump to be 100% though!

**Comment by insanelydeepak** [comment]
this one 
[ALC256.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/538035/ALC256.zip)

if doesn't work then needs codec dump

**Comment by maxexcloo** [comment]
[codec0.txt](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/538042/codec0.txt)
[codec2.txt](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/538041/codec2.txt)

**Comment by insanelydeepak** [comment]
try this 
 with or without codec commander 
[ALC256.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/538461/ALC256.zip)


don't forget to use without any profile CC

**Comment by maxexcloo** [comment]
Works fine! Is external microphone support supposed to work? If not it's
100%, unless I'm missing something!

**Comment by insanelydeepak** [comment]
can you report like this way 
Speaker ?
Headphone ?
Mic Internal ?
Mic External ?

**Comment by maxexcloo** [comment]
Speaker: Works Fine Unless Jack Plugged (Good!)
Headphone: Works Only When Jack Plugged (Good!)
Mic Internal: Works Always (Okay)
Mic External: Does Not Work

**Comment by insanelydeepak** [comment]
> Mic External: Does Not Work
is it detected ?  when you plugged ?

**Comment by maxexcloo** [comment]
Not that I can tell

**Comment by insanelydeepak** [comment]
try this one 
[ALC256.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/543545/ALC256.zip)

**Comment by maxexcloo** [comment]
I will have to get back to you as my laptop is currently at home, sorry 😞

**Comment by insanelydeepak** [comment]
> I will have to get back to you as my laptop is currently at home, sorry 😞
sure take your time

**Comment by duguzuyang** [comment]
I am also using Dell XPS 13 9350 and having audio problems,

> insanelydeepak commented on Oct 21
> try this one
> ALC256.zip

V1:
Speaker: not working
Headphone: Not working, loud noise with low volume music

V2:
Speaker: working fine
Headphone: Not working, loud noise with low volume music

V3:
Speaker: working fine
Headphone: Not working, loud noise with low volume music

**Comment by nos1609** [comment]
@insanelydeepak How can I help you to make a fully working kext? I'm running 10.12.2 with v3 kext right now.

**Comment by insanelydeepak** [comment]
Hi sorry I was kinda busy
