### ISSUE TITLE
Patched alc298 applehda

### ISSUE THREAD

**Issue by buhlaze** [insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12#20]
can i get a patched alc298 applehda(279.48) for 10.12.5? I tried with mirone and get an "error patching xml" message. CloverHDA works great, but i really would like a patched uptodate applehda to have as well. Please and thank you.

**Comment by insanelydeepak** [comment]
here 

[AppleHDA-279.48-ALC298.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/1050230/AppleHDA-279.48-ALC298.zip)
