### ISSUE TITLE
macOS High Sierra 10.13 support?

### ISSUE THREAD

**Issue by mkaa00x** [insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12#21]
How can this be updated to support 10.13?

**Comment by insanelydeepak** [comment]
Hi 
no this will not work 10.13 , so I'm quite busy these days so didn't installed 10.13 yet 
this is not big deal you can make your own dummy kext for any OSX Version 

if you want to try I can make one for you

**Comment by egore24** [comment]
How do we go about getting this to work with 10.13? If you're busy, could you quick guide us on making the dummy kext? Thanks!

**Comment by insanelydeepak** [comment]
here it is , 
this is dummy kext for 10.13 (for ALC270)
replace files of your codec into this 


[CloverHDA 10.13 .zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/1448647/CloverHDA.10.13.zip)

**Comment by egore24** [comment]
Thanks for the 10.13 kext! I'm just not sure how to put alc288 codec information into the kext. I am assuming it's in the plist of the package contents, but I don't know which lines to alter. If you could show what needs to change, I probably could take it from there. Thanks!
