### ISSUE TITLE
ALC288 not working at all?!

### ISSUE THREAD

**Issue by macmeister1967** [insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12#22]
Not working at all on Acer Aspire V5-573 (ALC288)

I was trying to get Intel-HDMI-Audio working, but using ALC288.zip, this does not work... no audio input/output device found. Used HDEF patch for injection Layout ID=13

Reverted to AppleALC + lilu.kext and all working but HDMI audio :-1: 

Any ideas greatly appreciated... (PS. DSDT.aml and SSDT-5.aml so heavily edited now, don't know what HDEF and BOD3 are supposed to look like). BOD3 (Intel HDMI) is under SSDT-5 btw.

PS. I removed AppleALC to test your CloverHDA kext

**Comment by insanelydeepak** [comment]
> ot working at all on Acer Aspire V5-573 (ALC288)
>I was trying to get Intel-HDMI-Audio working, but using ALC288.zip, this does not work... no audio >input/output device found. Used HDEF patch for injection Layout ID=13
its working fine with majority of user's can , you have to figure out your issue 

>Reverted to AppleALC + lilu.kext and all working but HDMI audio 👎
AppleALC Layout13 and cloverHDA is same 

> Any ideas greatly appreciated... (PS. DSDT.aml and SSDT-5.aml so heavily edited now, don't know what HDEF and BOD3 are supposed to look like). BOD3 (Intel HDMI) is under SSDT-5 btw.
post your files , I will look

**Comment by macmeister1967** [comment]
OK, I will when I am using the laptop next...

many thanks...

**Comment by insanelydeepak** [comment]
until I'm going to close it and feel free to re-open

**Comment by macmeister1967** [comment]
I have the laptop out on loan at the moment (for a few more days) - I'll get onto this as soon as I get it back!
