### ISSUE TITLE
ALC256 (from dell 7559 i5-6300HQ) can't work

### ISSUE THREAD

**Issue by crackself** [insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12#23]
In OS10.12.5,try both `ALC256_v2 - Working Combojack` and  `ALC256` follow the install guide but can't make sounds work.
the code_dump from ubuntu showed:
```
Codec: Realtek ALC3246
Address: 0
AFG Function Id: 0x1 (unsol 1)
Vendor Id: 0x10ec0256
Subsystem Id: 0x10280706
Revision Id: 0x100002
```
[codec_dump.txt](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/1135411/codec_dump.txt)

**Comment by K0guma** [comment]
https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/issues/11
The newest comment have the patched hda. However the sound quality is a bit bad, so bare that in mind,

**Comment by crackself** [comment]
thanks，it seems named as the AppleHDA in L/S/E, should I remove that one?

**Comment by K0guma** [comment]
Yeah replace that one, make sure you install using kext installers such as Kext wizard

**Comment by crackself** [comment]
Understand!

**Comment by insanelydeepak** [comment]
is it worked ? 
I was quite busy

**Comment by crackself** [comment]
sorry for lated to feed back.That driver no luck for me.
![screen shot 2017-07-16 at 00 30 52](https://user-images.githubusercontent.com/16448332/28237870-fef3e91a-697a-11e7-8ebf-4ce22d1df69a.png)

[CLOVER.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/1150190/CLOVER.zip)
[boot.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/1150191/boot.zip)

**Comment by crackself** [comment]
Perfect work now ,thanks !!@insanelydeepak @K0guma 
[Audio-for_ALC256.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/1152445/Audio-for_ALC256.zip)

**Comment by insanelydeepak** [comment]
you can use AppleALC instead , using dummyKext  , use AppleALC+LILU layout 13 or whatever you want 


Enjoy Good Sound :)

**Comment by bozma88** [comment]
@insanelydeepak, I don't understand: does this solution (AppleALC) give superior audio quality than your CloverHDA? If so, why? Can you elaborate? Thank you!

**Comment by insanelydeepak** [comment]
>  I don't understand: does this solution (AppleALC) give superior audio quality than your CloverHDA? If so, why? Can you elaborate? Thank you!

cloverHDA and AppleALC layout 13 is made by me , so there is no difference in it 

Now why AppleALC (appleALC.kext + lily.kext you have to use both) just have to use kext from clover kext folder 

Now why not CloverHDA :-
1.install CloverHDA to S/L/E
2.need to apply cloverPatch

why I recommend AppleALC bcoz for normal user you don't have to care for clover patches and software updates , only one kext for all OSX version e.g 10.10 , 10.11,10.12,10.13 so on
