### ISSUE TITLE
ALC256 Static through headphones

### ISSUE THREAD

**Issue by RustyIsotope** [insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12#25]
Using the ALC256_v2 - Working Combojack patches I have audio working through both the combo jack and the speakers. However using headphones I get a static sounds through them until I hear a pop when the audio device shuts off. I am on a Dell 9350 using audio layout 13. Help would be much appreciated. Thanks.

**Comment by ZombieTheBest** [comment]
Same issue, XPS9350. That static is not present in Windows. 
One more thing I have noticed (maybe related to CodecCommander): sometimes after sleep audio is not working (you can still hear some distorted sound coming out). To make it working again you have to go to Settings -> Audio -> Input tab, then the sound works again. But if you close the settings window the sound will work for about 30-40 seconds and it will be again REALLY distorted. The only way to make sound working is keeping the audio input window open, or reboot the device.

**Comment by insanelydeepak** [comment]
did you use CodecCommander ?

**Comment by RustyIsotope** [comment]
Yes the latest build from RehabMan was used.

**Comment by insanelydeepak** [comment]
What about using SSDT-256.aml ?

**Comment by RustyIsotope** [comment]
Yep I have that too and have it in my sorted order list.

**Comment by insanelydeepak** [comment]
post codec_dump

**Comment by RustyIsotope** [comment]
OK I will have to make a Linux USB

**Comment by RustyIsotope** [comment]
In the ubuntu terminal I entered in "cat /proc/asound/card0/codec#0 > ~/Desktop/codec_dump.txt" but it says No such file or directory.

**Comment by insanelydeepak** [comment]
use this code

` ~/Desktop && mkdir CodecDump && for c in /proc/asound/card*/codec#*; do f="${c/\/*card/card}"; cat "$c" > CodecDump/${f//\//-}.txt; done && zip -r CodecDump.zip CodecDump
`

**Comment by RustyIsotope** [comment]
[codec_dump.txt](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/1167838/codec_dump.txt)

I think I got it.

**Comment by ZombieTheBest** [comment]
Saw your last update. Have you done something to Speakers audio quality? Seems A LOT better (less crackling)! I can still hear a static noise through headphones and a pop (sometimes loud) when the static noise goes off

**Comment by RustyIsotope** [comment]
Just installed your latest update. Speakers are perfect but the static is still present when using headphones.

**Comment by insanelydeepak** [comment]
I will look at your codec_dump and let you know progress

**Comment by RustyIsotope** [comment]
Just wondering if there has been any progress.

**Comment by insanelydeepak** [comment]
@RustyIsotope @ZombieTheBest 
try this 
[SSDT256.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/1186372/SSDT256.zip)

**Comment by bozma88** [comment]
With this version, I have HORRIBLE static noises through internal speakers for all the time the aps is powered on.
With your previous releases, no issues at all, not even in headphones.
I am starting to think there are different hw revisions of XPS 9360 audio device out there.

**Comment by insanelydeepak** [comment]
>  I have HORRIBLE static noises through internal speakers for all the time the aps is powered on.

stick to old one

**Comment by bozma88** [comment]
> stick to old one

Of course, it was just a feedback.

**Comment by insanelydeepak** [comment]
@bozma88 
> Of course, it was just a feedback.
I appreciate and welcome all feedback and tying to improve as much as I can 


currently I'm working on ALC256 more than 10 codecs all has same issue of distortion/crack sound , almost all has same input/output nodes , still trying to fix it

**Comment by RustyIsotope** [comment]
I can confirm that the new SSDT doesn't help with the static or crackling. I really do appreciate you spending the time on this though.

**Comment by RustyIsotope** [comment]
After some further testing, with the original SSDT-ALC256 there is no static or artifacts when playing audio through the internal speakers. When using the headphone port there is a constant static white noise but no crackling or artifacts. With this new SSDT you uploaded there is crackling and artifacts in both the speakers and headphones. With both there is an audible pop when the amp shuts off after not playing any audio for a bit.

**Comment by insanelydeepak** [comment]
@RustyIsotope  thanks for feedback 
I will post some progress soon

**Comment by RustyIsotope** [comment]
Just wondering if there is any update. Thanks.

**Comment by insanelydeepak** [comment]
yes progress are ready 
but I  don't have time post them , may be tomorrow 
however I will try to post in couple of days

**Comment by RustyIsotope** [comment]
Ok no worries

**Comment by insanelydeepak** [comment]
try this 

[alc_fix.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/1244373/alc_fix.zip)

**Comment by ZombieTheBest** [comment]
@insanelydeepak ran ./install.sh. static noise and audio pop still present for me when using headphones, I didn't noticed any difference in my case. Thank you for your hard work on this!

**Comment by RustyIsotope** [comment]
I just tested this out. For me the static seems to be much quieter than before but it is still present. Audio pop is still present. Definitely an improvement though.

**Comment by insanelydeepak** [comment]
> Also does that install.sh need a reboot to be applied?

prefer to restart

**Comment by insanelydeepak** [comment]
> audio pop still present for me when using headphones
@ZombieTheBest  try this for pop
https://www.macupdate.com/app/mac/29024/antipop

**Comment by insanelydeepak** [comment]
Hello everyone
you guys need custom profile for CodecCommander , default in CC is not good for you ..
due to lack of time  I'm unable to make one but you can do it yourself , enough examples are their for CC SSDT

**Comment by RustyIsotope** [comment]
Hi

No problem I can try to do it myself but could you link me to some examples or guides please? I don't really know where to start. 

Thanks again for your help.

**Comment by ZombieTheBest** [comment]
@insanelydeepak Now i have no more static through headphones, i don't really know how! Is the custom CodecCommander gonna fix the sometimes-lost-audio after sleep? Thanks!

**Comment by RustyIsotope** [comment]
@ZombieTheBest Hey can you upload your Clover folder for me? Thanks!

**Comment by ZombieTheBest** [comment]
@RustyIsotope Sure! here you have! 👍 

[EFI.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/1272402/EFI.zip)

**Comment by insanelydeepak** [comment]
> Now i have no more static through headphones, 
are you sure ?? what you did ? 

what about comboJack ?

**Comment by insanelydeepak** [comment]
> i don't really know how! Is the custom CodecCommander gonna fix the sometimes-lost-audio after sleep?

you don't need custom profile , custom profile for user who still have distortion or crackling sound from headphone , when default profile (which is made long time ago) fails

**Comment by ZombieTheBest** [comment]
@insanelydeepak Connected headphones again now, static is back, most on right headphone, but with a very very low volume (is okay for me). But I SWEAR this afternoon I had ZERO static. 

Oh okay! 'Cause sometimes when I connect headphones, or after sleep, i can't hear sounds until I go into SysPref->Sound->Input Tab, then sound works again. Don't know why.

**Comment by insanelydeepak** [comment]
for Sleep issue , modify your SSDT-ALC256.aml 
 ```
 "Perform Reset", 
            ">n", 
            "Send Delay", 
            0x0A, 
            "Sleep Nodes", 
            ">n"
```
try to change  >n to >y , for each one by one see result

**Comment by MuntashirAkon** [comment]
@insanelydeepak I think instructions for using a custom profile with CodecCommander should be added in the readme.txt for those who have distortion/crackling sound.

**Comment by Nihhaar** [comment]
@insanelydeepak The static sound is still there after applying install.sh and the new SSDT but only on the right headphone (previous it used to be on both sides). I don't know how to create a custom profile for CC, could you/anyone guide me though it? Thank you.

**Comment by insanelydeepak** [comment]
1. download codec commander latest version https://bitbucket.org/RehabMan/os-x-eapd-codec-commander/downloads/
2. here is SSDT-256.dsl https://bitbucket.org/RehabMan/os-x-eapd-codec-commander/src , use MaciASL to copy code from web and create new, paste, compile and save it as SSDT-256.aml (aml file ) 
3.use it in clover ACPI/Patched folder , make sure config.plist you added it to sorted list 

Reboot and see results

**Comment by Nihhaar** [comment]
Thanks for replying. With the current mentioned SSDT there is static sound on both left and right headphones, the one you attached long ago above was better as it has static sound only on one side. Also sleeping and waking on this SSDT is causing no audio.

**Comment by insanelydeepak** [comment]
i see 
try above version again , i will try to improve it and send me code_dump file

**Comment by Nihhaar** [comment]
Also I am not using sorted order, I am not patching any SSDTs, just adding add-on SSDT (like SSDT-PNLF.aml, etc..).

**Comment by Nihhaar** [comment]
Oh ok, currently I don't have linux at the moment, I will send you tomorrow codec dump. Thank you for looking into this.

**Comment by insanelydeepak** [comment]
>> Also I am not using sorted order, I am not patching any SSDTs, just adding add-on SSDT (like SSDT-PNLF.aml, etc..).
yeah no issue , make sure you have SSDT256 there and in .aml format

**Comment by Nihhaar** [comment]
Sorry, I've been late, here is the codec dump: 
[CodecDump.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/1810510/CodecDump.zip)

To be clear, this is the current status:
(i)Without SSDT codeccommander profile: sound through headphones(no static noises) + no sound through speaker

(ii)With Rehabman SSDT-ALC256.aml: sound on both speaker + headphones, but static noise on both left and right headphones.

> @RustyIsotope @ZombieTheBest
try this
[SSDT256.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/1186372/SSDT256.zip)

(iii)With this SSDT profile: sound on both speaker + headphones, but sometimes static noise on only right headphone and sometimes no static noise at all(this is good). Sometimes sleep/wake or insert/remove headphone toggles the static noise presence.

I sometimes didn't get any sound at all through headphones (triggering siri would enable sound again for few minutes) but I can't remember which profile this belongs to: (i) or (ii) or (iii), but likely (i). If i experience it again, I will inform you.

Thank you.

**Comment by Nihhaar** [comment]
And also the 4 applehda patches in config.plist are required, right?

**Comment by insanelydeepak** [comment]
>  And also the 4 applehda patches in config.plist are required, right?

yes 

without CodecCommander + SSDT , what your result ?

**Comment by Nihhaar** [comment]
> without CodecCommander + SSDT , what your result ?
No sound through headphones but sound works through speakers

**Comment by Nihhaar** [comment]
> (i)Without SSDT codeccommander profile: sound through headphones(no static noises) + no sound through speaker

Sorry tested this again, actually sound works through both speaker, and headphones with static noise on right headphone. (same as (iii)). 
Idk why my tests are varying, may be I wasn't remembering properly.

**Comment by Nihhaar** [comment]
Many times, if I get any static noise from my right headphone ((i) & (iii)), putting laptop to sleep and wake up instantly causes a small pop and in some cases, there will be no static noise at all.

But If there is no static noise, a sleep/wake or replugging headphone will most likely cause static noise through right headphone again.

**Comment by Nihhaar** [comment]
Hey!
Static noise gone after I upgraded to 10.13.5 and using your SSDT you attached above "SSDT256.zip". The default SSDT-ALC256 profile in RehabMan's repo still causes static noise though.

May be you should add this as alternative profile for ALC256!

**Comment by insanelydeepak** [comment]
> Static noise gone after I upgraded to 10.13.5 and using your SSDT you attached above "SSDT256.zip". The default SSDT-ALC256 profile in RehabMan's repo still causes static noise though.

it means everything is fine for you ? 

> May be you should add this as alternative profile for ALC256!

i will ask rehabman 

can you send me SSDT ??

**Comment by insanelydeepak** [comment]
than you 
i'm closing this now
