### ISSUE TITLE
ALC 269 Doesn't Work

### ISSUE THREAD

**Issue by kholisrag** [insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12#26]
Hello @insanelydeepak 
I'm using Asus X450JB and MacOS 10.12.3
this is my log,
[ALC269.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/1173840/ALC269.zip)
In system information it's list Intel High Definition Audio ID 13, but it's not worked...
I open System Preference > Sound > Output, it's not listed

**Comment by insanelydeepak** [comment]
can you try ALC269 all version ?  like VC and VB too

**Comment by kholisrag** [comment]
It's same...
I try all of it...
In the end I choose different driver.... and it's work...
Thanks... Sorry for troubled you....

**Comment by insanelydeepak** [comment]
good to know you got it working 

> Sorry for troubled you....

I always love to help , so trouble for me but I work on free time probably weekends so it took time and I always try to respond as fast as possible
