### ISSUE TITLE
ALC295 KabyLake Series : All sound devices recognized but no audio, mic works

### ISSUE THREAD

**Issue by sebasinparis** [insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12#27]
Hi, I've attempted to get it to work for the past few days to no avail. After installing AppleALC, applying the general 200 series patch with layout 28, the audio worked for like a day although it was lower than Windows. It then disappeared and hasn't come back since. I've reinstalled the OS combo update to get back to vanilla but that didn't help. The microphone actually works but the speakers don't, although they do show up as available. CodecCommander didn't help. Originally I tried using the AppleHDA patches which failed so I switched to AppleALC which worked for a day as I previously addressed. Here are the latest [changes](https://github.com/vit9696/AppleALC/commit/d49edbd6e46f961ec7cfd09b2bbee52cc1260d70) that were used to build it. I'm hoping you could add support for this new codec. Attached is my codec dump, config.plist, DSDT patched and various other files that could help. Thanks! The laptop is an [HP Pavillion x360 2017](https://support.hp.com/us-en/document/c05561157)
[Archive.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/1176318/Archive.zip)

**Comment by insanelydeepak** [comment]
>  I'm hoping you could support for this new codec. 

sure 

I will make patched AppleHDA and provide you when have time

**Comment by sebasinparis** [comment]
I appreciate it 😁

**Comment by insanelydeepak** [comment]
Hi 
try this 
[AppleHDA-279.48-ALC295.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/1186250/AppleHDA-279.48-ALC295.zip)

PS: make sure you must have FakePCIID+HDMI kext installed

**Comment by sebasinparis** [comment]
Hey 
The speakers work great. But there's one issue. The microphone detects sounds yet it's unable to process the input. Quicktime, Siri etc... are unable to record or listen to my voice. For example the internal mic in system preferences detects sounds and the input level moves accordingly, nowhere else can capture it. I tried creating a new profile in codec commander but wasn't sure what to put in the dictionary referring it. But besides that thank you for creating this!
[Archive.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/1189853/Archive.zip)

**Comment by insanelydeepak** [comment]
Hi 
this is initial version my focus only was speaker and Headphone , just verify both are working ?
also check Line-In(external mic working ) 

> I tried creating a new profile in codec commander but wasn't sure what to put in the dictionary referring it

you don't need codec_commander until I'm done , I will definitely make one if required

**Comment by sebasinparis** [comment]
I just tested them. The speakers work amazingly well, just as loud as Windows. Headphones work just as good, hot plugging is no issue. But the mic doesn't work on either. Even the one on the headphones which I assume is the Line-in. I've included the bdmesg and kextstat logs. Thanks again.
[Archive.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/1189901/Archive.zip)

**Comment by insanelydeepak** [comment]
try this 

[AppleHDA-279.48-ALC295.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/1199567/AppleHDA-279.48-ALC295.zip)

**Comment by sebasinparis** [comment]
Hey. Thanks again for taking your time to help this community. But first, you need to know that yesterday I ran the full 10.12.6 5GB update to bring some files back to vanilla after pip started giving incessant errors and refusing to update. Afterward, the speakers stopped working which was expected since the kext was overwritten. So I reinstalled the first AppleHDA kext you sent. The speakers haven't worked since. They show as available though. I've rebooted and reinstalled the kext numerous time with the same result. Everything else still worked the same as my earlier post.

So I'm not sure if I'm still qualified to do the testing since I somehow ruined the speakers through an update. But nevertheless I tested the new kext. With it:
1. The speakers are shown as available but are nonfunctional. Let's just assume that had I not ran the macOS update over my current install, they'd still work like earlier. Since even if I install the first one you sent me, there's no sound either.
2. Headphones work great, hot pluggable. One thing I noticed though, even if you mute the laptop, music still plays at the bare minimum volume on them. Maybe the headphone port continuously runs when there's sound?  
3. With the new kext, there's no microphone available at all. Doesn't even show.
4. So in conclusion, with the new kext, I get no sound from speakers, Headphones work but mic is unavailable. When I install first HDA kext I get no sound, headphones work, mic is available but no input.

I'm tempted to reinstall Sierra on my hack again and start over to get the sound working again. It was and is still mostly vanilla as it's hotpatched so I'm not sure how running an update could have killed the audio. But if reinstalling it will further our progress then I'm willing. Let me know.

I've attached my ioreg, bdmesg, hda kextstat, config, patches, screenshots etc... Thanks again!
[Archive.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/1199875/Archive.zip)

**Comment by sebasinparis** [comment]
I think my mic might be broken as it doesn't work anymore. Both on macOS & Windows. I might start a warranty claim. That explains why my speakers haven't worked on the OS for the past few days. When it's repaired, I can start testing again. Thanks.

**Comment by insanelydeepak** [comment]
so I'm closing this issue till you available .
feel free to re-open whenever required 

hope you get it repaired 
GoodLuck

**Comment by sebasinparis** [comment]
Hey,
I'm not sure how to reopen this issue but I got a new replacement laptop. I installed the second kext. Unlike the first one you sent, the mic is unavailable. The speakers are but they don't work. You can have a look at the files here to verify. Thanks!
[Archive.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/1226349/Archive.zip)

**Comment by insanelydeepak** [comment]
install First kext and post result I will start from first place

**Comment by sebasinparis** [comment]
No problem. I've reinstalled the first kext. But for some odd reason the speakers don't produce any sounds, unlike the very first time I installed it two weeks back. The headphones do work fine but the mic doesn't pick up any sound. I've attached the files as requested.
Btw I installed the AppleALC kext to text and with the layout 28 everything works including the mic. Although the sound does occasionally die after sleep. But it's nowhere near as loud or full as when your kext worked a while back. Perhaps you could take some clues from its resources to complete the first kext. Thank you!
[Archive.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/1227170/Archive.zip)

**Comment by insanelydeepak** [comment]
thanks 
I will come up with some progress soon

**Comment by sebasinparis** [comment]
Great! Thanks for taking your time to do this.

**Comment by sebasinparis** [comment]
Hi,
I'm not sure how to say this but everything that I've said previously was inaccurate. First, my laptop's audio devices were defective & I had an incorrectly configured clover folder. My DSDT was carelessly hotpatched, my USBs weren't even properly configured. And my computer would often reboot during sleep or loose bluetooth etc... It was just not good enough for issue reporting.
Which must have hindered our progress or made you do unnecessary changes to what was essentially a perfect kext. If you have indeed been working on it for the past few days, I'd like to apologize for wasting your time. Everything that I reported earlier as not working has been fixed by a clean install and a 100% properly configured static patched system with the assist of rehabman. All my previous issues are non existant.

I reinstalled the first kext and everything works including the mic unlike my earlier reports. The speakers work and are a definite improvement over the appleALC kext as the sound is "fuller". The mic works with and without headphones. Headphones work and hotplug. Essentially you had it right the first time.
The one and only issue is even if you mute the sound, you can still hear it playing at a very low volume. Yes I did bring my speakers up to my ears haha. The headphones do it too.  It's almost like background noise but the speakers & headphones definitely don't shut off at the lowest possible volume. It's really the only thing you could improve, I hope you can find clues in this new ioreg and the subsequent files included.
Thanks for your help and sorry for wasting your time earlier. All I had to do was switch to static patching and get a new laptop.
[Config.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/1254289/Config.zip)

**Comment by insanelydeepak** [comment]
Hi 

can you report like 
Speaker = working ? or not 
Mic Internal = ? 
Headphone = ? 
ExternalMic (Line-in) = ?

**Comment by sebasinparis** [comment]
Hey

Speakers work.
Internal mic works.
Headphones work 100% like normal.
External mic works fine. I connected an external webcam and the mic on it worked. 

And mute definitely doesn't work. It just brings the volume down to a barely audible volume with a tiny bit of static noise. Great work and thanks!

**Comment by insanelydeepak** [comment]
let me make some progress for mute too

**Comment by insanelydeepak** [comment]
try this 

[AppleHDA-279.48-ALC295.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/1269604/AppleHDA-279.48-ALC295.zip)

**Comment by sebasinparis** [comment]
Hi, muting still doesn't work. Don't know if it's the song choice, but when it's muted; you can now barely hear it with the speakers. Like your ear literally, has to be touching the speaker grill to hear the faint noise coming through despite the mute. On the headphones though, it's pretty clear the sound is still on. 

Everything else works fine just like earlier. Is there anything specific I can test or send to you to help you with the progress? Thanks.
[09:02:17-ALC95.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/1271975/09.02.17-ALC95.zip)

**Comment by insanelydeepak** [comment]
Try this 

[ALC295.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/1272329/ALC295.zip)

**Comment by sebasinparis** [comment]
Hey,
Both kexts did the same thing. Same as last time, everything works except the mute. Try to look at the AppleALC kext, mirone's 295 recources have a working mute. With it, the sound is pedestrian compared to what you've created though. I don't know how you did it but gets so loud I'm actually afraid to go over a certain volume. Seriously the sound is crisp. Even if it can't mute, it's my new default sound kext. And that makes it worth it. Thanks.

**Comment by insanelydeepak** [comment]
> With it, the sound is pedestrian compared to what you've created though. I don't know how you did it but gets so loud I'm actually afraid to go over a certain volume. Seriously the sound is crisp. Even if it can't mute, it's my new default sound kext.

what it means ? 

I know mute is not working and I'm working with it 

you are comparing both so tell me which is good enough ?

**Comment by sebasinparis** [comment]
Essentially I was letting you know that even though the mute works on the AppleALC kext, I'm still going to use your kext because it sounds way better. The other ALC kext is more tailored towards last year Pavillion as opposed to mine. 
Yours is optimized better and apart from the muting issue, you've perfected the kext. I appreciate it. Even if it's never fixed, I'll keep using it.

**Comment by insanelydeepak** [comment]
try this 

[ALC295_test.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/1290240/ALC295_test.zip)

**Comment by insanelydeepak** [comment]
so I'm closing this issue till you available .
feel free to re-open whenever required

hope you get it repaired
GoodLuck

**Comment by wlals0874** [comment]
Hello I am using HP - BC225TX. But I put the AppleHDA that was given by insanelydeepak into EFI - Clover - Kexts - Other, and I can not get any devices .... How do I install it?

**Comment by insanelydeepak** [comment]
use any kexts install to just ,

**Comment by wlals0874** [comment]
For example, what are some things?
![2017-12-15 10 51 16](https://user-images.githubusercontent.com/34575495/34044985-8ba806e2-e1ea-11e7-86f4-dcced23cf6e3.png)

**Comment by insanelydeepak** [comment]
first remove this kext and use kext i send 
![34044985-8ba806e2-e1ea-11e7-86f4-dcced23cf6e3](https://user-images.githubusercontent.com/9814566/34045110-93a050ec-e1cd-11e7-85fb-305d84f5259d.png)

**Comment by wlals0874** [comment]
I deleted it. What can I put in now?

**Comment by insanelydeepak** [comment]
i dont remember what i send you , if it is AppleHDA or CloverHDA , you should install it , and use layout 13

**Comment by wlals0874** [comment]
![2017-12-15 11 01 40](https://user-images.githubusercontent.com/34575495/34045387-07bf7638-e1ec-11e7-90f0-761442a93b12.png)
![2017-12-15 11 04 30](https://user-images.githubusercontent.com/34575495/34045464-545f19d0-e1ec-11e7-99b1-69a62367aa93.png)
![2017-12-15 11 04 57](https://user-images.githubusercontent.com/34575495/34045480-65d8ffd2-e1ec-11e7-802a-8993e0eca7af.png)

I downloaded the ALC295 Test attached to insanelydeepak and put it in AppleHDA in EFI-CLOVER-Kexts-other.

Attached with EFI
https://drive.google.com/open?id=1W7Q1DN7UBkKTKAUovEB903yUb5naZCeR

**Comment by insanelydeepak** [comment]
you have to install it to SLE (System/Library/Extension)

**Comment by wlals0874** [comment]
OK S/L/E and reboot does not work. Could you give me a look at IOREG and Config , DSDT ?

[김지민의 MacBook Pro.ioreg.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/1562984/MacBook.Pro.ioreg.zip)
[config.plist.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/1562987/config.plist.zip)
![2017-12-15 11 20 43](https://user-images.githubusercontent.com/34575495/34045961-9b5dc56e-e1ee-11e7-870d-acab186d8bbe.png)
[DSDT.aml.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/1562991/DSDT.aml.zip)

**Comment by insanelydeepak** [comment]
use this dsdt 
[DSDT.aml.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/1563004/DSDT.aml.zip)

**Comment by wlals0874** [comment]
I get a lot of ACPI errors at boot time and I do not like DSDT patches at all. And the audio is also poor.

**Comment by insanelydeepak** [comment]
> I do not like DSDT patches at all

i just applied IRQ Fix patch from rehabman which is must to load AppleHDA (LAPTOP only)

poor like ?

**Comment by wlals0874** [comment]
After booting, I took a movie with sound.
[KakaoTalk_Video_2017-12-15-23-42-30.mp4.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/1563058/KakaoTalk_Video_2017-12-15-23-42-30.mp4.zip)

**Comment by insanelydeepak** [comment]
do you remember AppleALC work for you with DSDT ?

**Comment by wlals0874** [comment]
AppleALC was recognized without an IRQ patch, and only the speakers came out. The audio object was 3 at that time.
AppleALC: Microphone OK, Speaker Recognized but No Sound, Headphone OK

**Comment by wlals0874** [comment]
Also, all IRQ patches will disappear from all DSDT patches.

**Comment by wlals0874** [comment]
Can you ask for help with Team Viewer?

**Comment by insanelydeepak** [comment]
use native AppleHDA + AppleALC + Old DSDT 
use layout 13 , appleAlc has my files

**Comment by insanelydeepak** [comment]
> Can you ask for help with Team Viewer?

sorry , very limited time

**Comment by wlals0874** [comment]
Does not fix the speakers in Applealc.kext? Everything else works.

**Comment by insanelydeepak** [comment]
send me DSDT

**Comment by insanelydeepak** [comment]
try this 
[DSDT.aml.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/1656229/DSDT.aml.zip)

**Comment by wlals0874** [comment]
DSDT 배터리 오류가 발생하여 부팅되었습니다. Applealc은 연사를 위해 일하고 있지 않습니다.

**Comment by wlals0874** [comment]
DSDT Battery I got an error and booted up. Applealc is not working on the speakers.

**Comment by insanelydeepak** [comment]
check AppleHDA loaded or not ?

**Comment by insanelydeepak** [comment]
use Old non patched DSDT and send me Clover folder

**Comment by Woodycheung** [comment]
hello @insanelydeepak 
I've a problem while using the alc295 sound card on Mojave 10.14.4.
I've already using hackintool to do framebuffer for hdmi ports and it's success to get the hdmi output, but no hdmi audio selection. How can I solve it?Also using IOREG to check the connector type for my FrameBuffer@1, the connector-type still is 00 04 00 00 not 00 08 00 00, not likes rehabman said will change,I also try all id I can use, but no luck. Please help if you have time.Thanks.

**Comment by wlals0874** [comment]
> hello @insanelydeepak
> I've a problem while using the alc295 sound card on Mojave 10.14.4.
> I've already using hackintool to do framebuffer for hdmi ports and it's success to get the hdmi output and my internal speakers is work ,mic work,Bluetooth earphone also work , but no hdmi audio selection. How can I solve it?Also using IOREG to check the connector type for my FrameBuffer@1, the connector-type still is 00 04 00 00 not 00 08 00 00 but I already add the frambuffer in my config device/properties con1 type to HDMI and this not likes rehabman said will change after do this patches,I also try all id I can use, but no luck. Please help if you have time.Thanks.

Hello

**Comment by Woodycheung** [comment]
@wlals0874 you mean patch HDMI output? I just get the image no sound now.

**Comment by wlals0874** [comment]
> @wlals0874 you mean patch HDMI output? I just get the image no sound now.

Not even the current connection.

**Comment by Woodycheung** [comment]
Aftere I've try many times, first thing is you SMBIOS must be choose correctly, after that use the hackintools to do the framebuffer, restart you computer while connected the HDMI, open hackintools and select Framebuffer to 10.14, now you can change to connectors page , you will see one of ports will lighting.
Now you need to find out which index is your hdmi port, actually if you just have one port of HDMI/DP
that should be index 1 and the busid will be 0x01 ,also the pipe must be 18. once you find another lighting port, go to patch page and select Devices/ Properties , Connectors and VRAM in General, and go to Advanced select Disable eGPU ,VRAM 2048MB ,Enable HDMI20(4K), Hotplug Reboot Fix, Device ID( what you're using) and click Generate Patch. Now you will get a patch.

**Comment by insanelydeepak** [comment]
Hi 
@Woodycheung is there no connector patch for your graphics?? 
why not use WEG ?

**Comment by wlals0874** [comment]
![Screen Shot 2019-05-06 at 10 24 16 PM](https://user-images.githubusercontent.com/34575495/57228030-c87def80-704d-11e9-90a2-f0a651cc6d45.png)
![Screen Shot 2019-05-06 at 10 24 44 PM](https://user-images.githubusercontent.com/34575495/57228033-c9af1c80-704d-11e9-939e-49e73d835f6e.png)
d

How do I patch the frame buffer to 10.14?

**Comment by insanelydeepak** [comment]
@wlals0874  i don't have much info about patching framer buffer bcoz i never needed it , so it think you should ask headkaze or others know better what these patches actually do
