### ISSUE TITLE
ALC256 Sound problem

### ISSUE THREAD

**Issue by PankovSerge** [insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12#28]
Hello, @insanelydeepak! 
I have a problem with sound on my dell xps 13 with alc256. 

[YouTube video with problem description](https://youtu.be/KVstNpCt0VU)
and it's not a hardware problem, sound works perfectly on linux.

10.12.6

Files in attachment:
1. Screenshot of intel hda
2. bdmesg log
3. config.plist
4. ioreg
5. kext stat for apple hda
6. CodecDump from linux

[ALC256_Trouble.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/1178514/ALC256_Trouble.zip)

**Comment by insanelydeepak** [comment]
you need to install FakePCIID + HDMI kext 

https://bitbucket.org/RehabMan/os-x-fake-pci-id

this below issue for reference 
#11

**Comment by PankovSerge** [comment]
FakePCIID + HDMI kext does not help, same here

**Comment by insanelydeepak** [comment]
Hello 

can you explain more ?  video shows you have audio working on youtube

**Comment by insanelydeepak** [comment]
#25 

try SSDT + Codec commander I post

**Comment by PankovSerge** [comment]
Hello, @insanelydeepak! If you watch the video in the headphones, you will hear that there are multiple lags, shutter, and crackling sounds. 

+ of course i use a SSDT-ALC256.aml in Sorted Order + Codec commander. 

If you need some more info, files, logs, i can easily provide it.

**Comment by PankovSerge** [comment]
Same. Sound works, but with delay, shutter, etc.

SSDT from [#25](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/issues/25)

cloverHDA kext from [ALC256_v2 - Working Combojack.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/commit/1a782e8fd5bfac549abd51a22bdeff280d1419a4)

Files in attachment:
[latest_alc256_aml.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/1188336/latest_alc256_aml.zip)

Screenshot of intel hda
bdmesg log
config.plist
ioreg
kext stat for apple hda
CodecDump from linux

**Comment by insanelydeepak** [comment]
Thanks 

I will come with some new progress soon

**Comment by ZombieTheBest** [comment]
I don't have this problem but sometimes Audio disappear. If I go to` Sys Settings -> Sounds -> Input` sounds works again. Sometimes I have to keep Input window opened in background. Try to test with Input window open, maybe it's similar to my problem.

**Comment by MuntashirAkon** [comment]
@ZombieTheBest Did you install `CodecCommander.kext`?

**Comment by ZombieTheBest** [comment]
Yes I did

Il 03 Dic 2017 08:29, "Muntashir Al-Islam" <notifications@github.com> ha
scritto:

**Comment by insanelydeepak** [comment]
which one version 1 or 2 ??

**Comment by insanelydeepak** [comment]
Hi 
i'm closing this issue , you need help and available feel free to re-open
