### ISSUE TITLE
AC887 - Cant get it to work

### ISSUE THREAD

**Issue by diogoribeiro09** [insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12#29]
Hello,
I've been trying to figure out what's happening with my audio (lack of it, actually) on Sierra but I still can't figure it out. I keep having no output/input devices listed. 
I have a Xonar DX 5.1  also connected to the pc (for windows) can it be affecting the patches? 

Am I missing something?

Thank you in advance for your help.
Kind Regards

[DR_ErrorReport.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/1213302/DR_ErrorReport.zip)

**Comment by insanelydeepak** [comment]
post your DSDT

**Comment by insanelydeepak** [comment]
it seems AppleHDA not loaded  , did you install cLoverHDA ??

**Comment by diogoribeiro09** [comment]
Hello, thank you for your quick response. It is a fresh installation so I suppose AppleHDA should be already included (although the kext is not present on S/L/E). I installed CloverHDA with EastkextPro as suggested (and i confirme it is on S/L/E).

Should I try to 'recover' AppleHDA following Toleda guide (Assuming that somehow my Kext disappeared ?)

I'm currently stuck on traffic I'll post the DSDT asap.

**Comment by insanelydeepak** [comment]
.bak files created by kextutility 
try this DSDT 

put it in Clover/ACPI/patched

[DSDT.aml.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/1224903/DSDT.aml.zip)

**Comment by diogoribeiro09** [comment]
Hello again, 
im sorry for not answering soon but wasn't near my computer. 
I've added the file as u advised to my EFI partition C/A/P but i still have no device listed :/

What do you reckon ? Again, i have a Xonar DX connected on a PCI-E slot, can it be interfering ?

**Comment by insanelydeepak** [comment]
type kextstat in terminal send output

**Comment by diogoribeiro09** [comment]
Hello,
There you go.

[kextstat_dr.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/1245717/kextstat_dr.zip)

**Comment by insanelydeepak** [comment]
Hi
did you try AppleALC ??

**Comment by insanelydeepak** [comment]
so I'm closing this issue till you available .
feel free to re-open whenever required
