### ISSUE TITLE
Not Working on HP Envy dv6

### ISSUE THREAD

**Issue by hgarca089** [insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12#3]
Here are my files. Thx for your time, help and hard work on this.
![audio prop](https://cloud.githubusercontent.com/assets/22920407/19493116/68c2e21e-9547-11e6-8593-07a24fda4d9a.jpeg)
[bootlog.log.txt](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/537179/bootlog.log.txt)
[CLOVER.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/537178/CLOVER.zip)
[config.plist.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/537177/config.plist.zip)
[Jonathan’s MacBook Pro.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/537180/Jonathan.s.MacBook.Pro.zip)
[kextstat.txt](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/537176/kextstat.txt)

[DSDT.aml.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/537186/DSDT.aml.zip)

**Comment by insanelydeepak** [comment]
what codec ??

**Comment by hgarca089** [comment]
IDT high definición audio id 111D. 76E0 so 92HD91BXX

Thx

**Comment by insanelydeepak** [comment]
did you install CloverHDA ??

**Comment by hgarca089** [comment]
Yes I did

**Comment by insanelydeepak** [comment]
try this one 

[IDT92HD91BXX.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/537955/IDT92HD91BXX.zip)

**Comment by hgarca089** [comment]
there one 2 kext files one in v1 folder and one loose file, trying with loose file 1st

**Comment by hgarca089** [comment]
see more details of intel sound 
![better](https://cloud.githubusercontent.com/assets/22920407/19506089/64d28408-9596-11e6-8693-c9a4c9d2b25d.jpeg)

**Comment by hgarca089** [comment]
but still no sound

**Comment by insanelydeepak** [comment]
tried both version ? 
any input output visible in preferances ?

**Comment by hgarca089** [comment]
[bootlog.log.txt](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/537967/bootlog.log.txt)
do I need to have cloverhda in efi\kext\other folder?
I am installing kext files with ikert app.

**Comment by hgarca089** [comment]
no output visible under pref\sound

**Comment by insanelydeepak** [comment]
look at kextstat | grep -y AppleHDA

**Comment by hgarca089** [comment]
should I try 2nd kext file or should I wait for your input...
Jonathans-MacBook-Pro:~ jonathan$ kextstat | grep -y AppleHDA
   97    1 0xffffff7f82819000 0x1d000    0x1d000    com.apple.driver.AppleHDAController (276.26) D0953002-6091-376F-8E0F-33B65F42CEF9 <96 95 83 12 7 6 5 4 3 1>
  122    0 0xffffff7f82bc7000 0xb4000    0xb4000    com.apple.driver.AppleHDA (9276.26) 7611D43E-12FE-3228-A6D3-9C99A5D030CC <121 104 97 96 95 83 6 5 4 3 1>
Jonathans-MacBook-Pro:~ jonathan$

**Comment by hgarca089** [comment]
do I need to see speakers under intel audio?

**Comment by insanelydeepak** [comment]
these three version one by one 

[IDT92HD91BXX_v2.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/537977/IDT92HD91BXX_v2.zip)
[IDT92HD91BXX_v3.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/537978/IDT92HD91BXX_v3.zip)
[IDT92HD91BXX_v1.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/537979/IDT92HD91BXX_v1.zip)

**Comment by hgarca089** [comment]
ok will do now

**Comment by hgarca089** [comment]
tried the v1 folder form 1st zip you sent and have sound now

**Comment by hgarca089** [comment]
![1](https://cloud.githubusercontent.com/assets/22920407/19506431/81912c36-9599-11e6-80ed-1afa498dcdae.jpeg)
![2](https://cloud.githubusercontent.com/assets/22920407/19506434/84db1000-9599-11e6-9d54-8fa57ca2f101.jpeg)

**Comment by hgarca089** [comment]
have internal speakers as output option but no input... should I see mic in there?

**Comment by hgarca089** [comment]
do you want me to try the las 3 zip files?

**Comment by insanelydeepak** [comment]
yep , will be better

**Comment by hgarca089** [comment]
ok, will do now

**Comment by hgarca089** [comment]
ok, version1 of those 3 files sound ok, output internal speakers input none
going to 2dn now

**Comment by hgarca089** [comment]
v2 same results

**Comment by insanelydeepak** [comment]
now which version has working ouput/input as des
Speaker =?
Headphone = ?
Mic = ?
External mic = ?

**Comment by hgarca089** [comment]
all of them show 
![better](https://cloud.githubusercontent.com/assets/22920407/19506709/cbc8cbc2-959b-11e6-87a2-0f111f9bf56f.jpeg)
but only 
![input](https://cloud.githubusercontent.com/assets/22920407/19506759/1a0bd72a-959c-11e6-9fa5-13e14c4de5b3.jpeg)

**Comment by hgarca089** [comment]
it shows only speakers on the prefer... no input or any other outputs. I read in the other post the gay with del eps about a file codecommander... do I need that?

**Comment by hgarca089** [comment]
I noticed that I don't see speaker under intel high def audio on sysinfo

**Comment by hgarca089** [comment]
I see external microphone/iphone headset
headphone
internal mic
hdmi/displayport output

**Comment by hgarca089** [comment]
let me know if you are going to bed.. I now it is late at least here in Toronto

**Comment by insanelydeepak** [comment]
> let me know if you are going to bed.
day here 

can you provide codec_dump ?

**Comment by hgarca089** [comment]
how do i do that?

**Comment by insanelydeepak** [comment]
here you go 
http://osxarena.com/2016/04/applehda-patch-request/

**Comment by hgarca089** [comment]
cat: /proc/asound/card0/codec#1: No such file or directory

tried codec#0 with same results

**Comment by insanelydeepak** [comment]
Use this 
cd ~/Desktop && mkdir CodecDump && for c in /proc/asound/card*/codec#*; do f="${c/\/*card/card}"; cat "$c" > CodecDump/${f//\//-}.txt; done && zip -r CodecDump.zip CodecDump

**Comment by hgarca089** [comment]
cd ~/Desktop && mkdir CodecDump && for c in /proc/asound/card/codec#; do f="${c/\/*card/card}"; cat "$c" > CodecDump/${f//\//-}.txt; done && zip -r CodecDump.zip CodecDump
cat: /proc/asound/card/codec#: No such file or directory

**Comment by insanelydeepak** [comment]
You need to do this in Linux 
Use live USB

**Comment by hgarca089** [comment]
oh ok, going there now

**Comment by hgarca089** [comment]
do i need codecommander.kext on my laptop?

**Comment by insanelydeepak** [comment]
Your can try v1 with codec commander 
Sometimes requires sometimes not

**Comment by hgarca089** [comment]
same results in ubuntu live

**Comment by hgarca089** [comment]
codeccommnade goes to efi\clover\kexts\other or have to be installed to s/l/e?

**Comment by hgarca089** [comment]
got it....

**Comment by insanelydeepak** [comment]
You can use it from sle or clover kexts

**Comment by hgarca089** [comment]
[CodecDump.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/538087/CodecDump.zip)

**Comment by insanelydeepak** [comment]
For codec dump use link above posted, go through it

**Comment by hgarca089** [comment]
ok

**Comment by hgarca089** [comment]
wil do it tomo... thx for your help!!! have a great night

**Comment by insanelydeepak** [comment]
Sure will look dumo and report 

Sleep well

**Comment by insanelydeepak** [comment]
try this 

[IDT92HD91BXX.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/538524/IDT92HD91BXX.zip)
with or without codec commander

**Comment by hgarca089** [comment]
Tried version one of last zip file you attached here and got same results only one output device (internal speakers) and no input... sound quality ok.
do you have a link for that codec commander?

**Comment by hgarca089** [comment]
Version 2 shows NO OUTPUT devices at all, and no input, no sound...., went back to version one

**Comment by insanelydeepak** [comment]
> do you have a link for that codec commander?

https://bitbucket.org/RehabMan/os-x-eapd-codec-commander/downloads

**Comment by hgarca089** [comment]
ok, will install it right now

**Comment by hgarca089** [comment]
I sent all the files with codec dump file this morning

**Comment by insanelydeepak** [comment]
> I sent all the files with codec dump file this morning

yes received

**Comment by hgarca089** [comment]
good, installed codec commander, no differences only one output device  internal speakers and no input devices.... do I need to do something with codec commander or just install to sle?

**Comment by insanelydeepak** [comment]
is your Headphone working ??

**Comment by hgarca089** [comment]
when I connect headset, in output devices I don't see speaker any more I see headphones but no input, sound is good on the headset

**Comment by hgarca089** [comment]
I was able to record a clip with webcam but no sound...

**Comment by insanelydeepak** [comment]
> when I connect headset, in output devices I don't see speaker any more I see headphones but no input, sound is good on the headset
ok now got you 
Speaker and Headphones working ? right 

Mic internal and External not working ?

**Comment by hgarca089** [comment]
exactly no mic working

**Comment by insanelydeepak** [comment]
> exactly no mic working

is getting detected ? in prefer input ?

**Comment by hgarca089** [comment]
no,  nothing has shown as input device

**Comment by insanelydeepak** [comment]
try this 
[IDT92HD91BXX.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/540781/IDT92HD91BXX.zip)

**Comment by hgarca089** [comment]
V1 output ok, shows internal mic in the input device, tried to record a sound clip and a movie clip and no sound... when connected external mic still was showing internal and no sound recorded...will try v2 now

**Comment by hgarca089** [comment]
v2 exactly the same as version 1

**Comment by hgarca089** [comment]
output is ok, it switches between internal speakers and headphone when I connect headset

**Comment by insanelydeepak** [comment]
> hows internal mic in the input device, tried to record a sound clip and a movie clip and no sound

try to use QuickTime to record

**Comment by hgarca089** [comment]
tried it already with v1 and v2.... no sound...

**Comment by insanelydeepak** [comment]
try this one 

[IDT92HD91BXX.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/540807/IDT92HD91BXX.zip)

**Comment by hgarca089** [comment]
V1 of last file no sound recorded with internal and external mic. output sound ok... going to v2 now

**Comment by hgarca089** [comment]
V2 exactly same no sound recorded with both mics... going to v3

**Comment by hgarca089** [comment]
V3 same ......

**Comment by hgarca089** [comment]
going to bed now.. we can continue tomo night, thanks for all your time!! have a good night

**Comment by insanelydeepak** [comment]
is your mic working in Other OS ??

**Comment by hgarca089** [comment]
yes, windows 10 is ok. I tried today a hdmi monitor with builtin speakers and no sound in the monitor only in the internal speakers, not showing hdmi as an output device in preferences

**Comment by insanelydeepak** [comment]
> I tried today a hdmi monitor with builtin speakers and no sound in the monitor only in the internal speakers, not showing hdmi as an output device in preferences

HDMI requires Connector patches/DSDT etc , may be you lack one it

**Comment by hgarca089** [comment]
hdmi sound is not that important, internal and external mics yes, waiting for a wifi mini pci-e to replace intel one with atheros to have wifi...

**Comment by insanelydeepak** [comment]
try this 

[IDT92HD91BXX.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/543562/IDT92HD91BXX.zip)

can you notice is it accepting audio or not while thumping on mic ?

**Comment by hgarca089** [comment]
Hi, I tried the 4 versions..... same results in all of them. Sound is ok internal speakers and headphones. Notice in the red circle that those devices show more details compared to internal Mic, that one does not change when I insert the external Mic (like the internal speakers does when I insert the headset plug). Mic does not show any input level and any details under TYPE, tried to record sound with quicktime and nothing with internal and external mic, tried to record a video clip with camera and same no sound....
THX!!!

![internal speakers](https://cloud.githubusercontent.com/assets/22920407/19608939/3e3a1c8a-97a2-11e6-92d7-31f27979334d.jpeg)
![headphones](https://cloud.githubusercontent.com/assets/22920407/19608946/4a76200c-97a2-11e6-83d0-bb01c6ae88c0.jpeg)
![mics](https://cloud.githubusercontent.com/assets/22920407/19608951/4dc9cc7c-97a2-11e6-83f5-1857419e3f62.jpeg)

**Comment by insanelydeepak** [comment]
try this 
[IDT92HD91BXX.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/545612/IDT92HD91BXX.zip)

**Comment by hgarca089** [comment]
Tried that one: output device shows unknown and no sound, if I plug headphones it changes to headphones and there is sound on them if I remove them it stays with headphones but after that no sound with and without headphones....... input devices: empty (no device)....

**Comment by hgarca089** [comment]
BTW this morning I tried applealc.kext (after removing cloverhda.kext) and have the same issues as before sound on internal speakers and headphones but nothing in MIC

**Comment by insanelydeepak** [comment]
try this again 
with or without codeccommander 
and notice is it accepting audio while recording ? 
https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/blob/master/Laptop/IDT92HD91BXX_v1.zip

**Comment by hgarca089** [comment]
with this one sound is find (internal speakers and headphones) but no input device is listed....

**Comment by hgarca089** [comment]
do I need to do something with that plist file inside de attachment? I only used cloverhda.kext...

**Comment by insanelydeepak** [comment]
> do I need to do something with that plist file inside de attachment? I only used cloverhda.kext...

plist has info to apply CloverPatches , if missing use it else let it

**Comment by hgarca089** [comment]
I not sure if I know how to  do that... I will put here my config file and if you have time take a look to see if anything is missing...[config.plist.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/545659/config.plist.zip)

**Comment by hgarca089** [comment]
Hi for the sound part (internal speakers and headphones, switching between them) the last driver is the best one...

https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/blob/master/Laptop/IDT92HD91BXX_v1.zip

but this one does not show the mic at all....

**Comment by insanelydeepak** [comment]
> Sound part (internal speakers and headphones, switching between them) the last driver is the best one...

can you provide ?

**Comment by hgarca089** [comment]
![internal](https://cloud.githubusercontent.com/assets/22920407/19624283/885a1c00-98bc-11e6-9a3b-ecad4d84aef0.jpeg)
![mic](https://cloud.githubusercontent.com/assets/22920407/19624284/8a7b538c-98bc-11e6-86f8-5178034c93ff.jpeg)

**Comment by hgarca089** [comment]
His found this post https://www.tonymacx86.com/threads/guide-hp-dv6-7040tx-clover.151708/ and installed voodoo hda and works ok.... take a look: sound perfect with internal speakers and headphones, internal mic does not work, but headphones mic works perfectly, I was able to record with QT a video clip and sound clips......
![sysinfo](https://cloud.githubusercontent.com/assets/22920407/19624441/4f79eba6-98c4-11e6-85b7-ff0b03d095e0.jpeg)
![external](https://cloud.githubusercontent.com/assets/22920407/19624442/519370d8-98c4-11e6-8bed-8c992f684785.jpeg)
![mics](https://cloud.githubusercontent.com/assets/22920407/19624443/540ef076-98c4-11e6-819a-1926b3265fd5.jpeg)

**Comment by hgarca089** [comment]
HDMI sound is in the list but does not work witth this codec

**Comment by insanelydeepak** [comment]
Can you provide voodoo dumo?? 

> can you provide ? just post here
 
Ii need kext you saidis Best one

**Comment by hgarca089** [comment]
this one you sent (https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/blob/master/Laptop/IDT92HD91BXX_v1.zip) I the best driver for output sound (internal speakers/headphones switching) but no mic is listed/working....what is voodoo dump?

thanks

**Comment by hgarca089** [comment]
getdump here...
[getdump.txt](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/549457/getdump.txt)

**Comment by hgarca089** [comment]
Yes Windows 10 perfectly
I connect a HDMI monitor with built-in speakers and video was perfect but
no sound using HDMI... Just internal laptop speakers

**Comment by hgarca089** [comment]
any other inputs?

**Comment by insanelydeepak** [comment]
Hello 
Busy weekdays will look on weekends

**Comment by hgarca089** [comment]
Thanks.... The only thing that is not working now is the hdmi sound....

**Comment by insanelydeepak** [comment]
> Thanks.... The only thing that is not working now is the hdmi sound....

HDMI requires connector's patch according what graphics you have , DSDT/SSDT as well

**Comment by jefernandez** [comment]
Hi, 
I got the same issue in my HP Envy DV7 7203ss with IDT92HD91BXX. Audio output is working but input doesn't.

I attach the files.

[Archive.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/614433/Archive.zip)
![screen shot 2016-11-26 at 22 12 40](https://cloud.githubusercontent.com/assets/4927838/20643915/a056f6b4-b425-11e6-8ff4-a0cf67d7a044.png)

**Comment by jefernandez** [comment]
And besides, when I press bright up button, Sound is muted.

**Comment by insanelydeepak** [comment]
Hi sorry I was kinda busy
if you want we can continue

**Comment by jefernandez** [comment]
Yes, please.
I'd love to.

**Comment by jefernandez** [comment]
Tell me what do you need or what can I do

**Comment by insanelydeepak** [comment]
Hi 
we should start again ?

**Comment by insanelydeepak** [comment]
I assume you are not available to fix this issue 
for now I'm closing issue 
feel free to re-open issue 

Regards 
Deepak

**Comment by jefernandez** [comment]
Hello

Sorry, I have just read the message. Could we continue with the issue?

**Comment by insanelydeepak** [comment]
yes definitely

**Comment by jefernandez** [comment]
Great!
Please, tell me what do you need. What can we do?

**Comment by insanelydeepak** [comment]
post your codec_dump

**Comment by jefernandez** [comment]
Sure. 
There we go!

[codec_dump0.txt](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/1045615/codec_dump0.txt)
[codec_dump3.txt](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/1045616/codec_dump3.txt)

**Comment by insanelydeepak** [comment]
I assume you have OSX 10.12.5 , install using EasyKextPro and use Layout ID 13 

[AppleHDA-279.48-IDT92HD91BXX.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/1050245/AppleHDA-279.48-IDT92HD91BXX.zip)

**Comment by jefernandez** [comment]
Hi, 

We are close. Now I can see the input device in the preferences as you can see in the screenshot. But It doesn't work.

I attach my DSDT and my config.plist
[Archive.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/1063715/Archive.zip)




![screen shot 2017-06-09 at 12 18 49 1](https://user-images.githubusercontent.com/4927838/26971573-fdff21a2-4d0d-11e7-94e9-21c50ac807ce.png)

**Comment by insanelydeepak** [comment]
I think I did some mistake , let me correct it

**Comment by jefernandez** [comment]
Sure!

Thank you so much!!!!

**Comment by insanelydeepak** [comment]
Try this 
[IDT.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/1066242/IDT.zip)

**Comment by jefernandez** [comment]
Now everything is working properly!

That's great!! Thank you so much! You are the best!

**Comment by insanelydeepak** [comment]
wich version ??  so will commit in this repo

**Comment by jefernandez** [comment]
I can't remember. Let me check and I'll tell you

**Comment by jefernandez** [comment]
Hi, I have installed this one.
[AppleHDA.kext.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/1072520/AppleHDA.kext.zip)

I think it is version V2

**Comment by insanelydeepak** [comment]
install it again and check output/inout so we will better sure

**Comment by insanelydeepak** [comment]
v2 is same as IDT92HD91BXX_v1 , so you can use it for future reference 

Regards 
Deepak
