### ISSUE TITLE
ACL662 on Intel 8086:a170 Sunrise Point-H HD Audio

### ISSUE THREAD

**Issue by scerazy** [insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12#31]
Lenovo Thinkcentre M800, Sierra 10.12.6

No audio device in Preferences
[config.plist.txt](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/1224987/config.plist.txt)
[M800.ioreg.txt](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/1224986/M800.ioreg.txt)
[bdmesg.txt](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/1224980/bdmesg.txt)
![hd audio](https://user-images.githubusercontent.com/3018438/29315782-eef24926-81bc-11e7-805c-11fa49ae5ac5.jpeg)
[kextstat_AppleHDA.txt](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/1224981/kextstat_AppleHDA.txt)
[CodecDump.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/1226074/CodecDump.zip)

sc

**Comment by insanelydeepak** [comment]
post codec dump

**Comment by scerazy** [comment]
Added to first post, thanks

**Comment by scerazy** [comment]
Is it likely that this ACL662 might be supported?

**Comment by insanelydeepak** [comment]
try this one , remove cloverHDA.kext and disable clover patches 
send output of kexstat 

[AppleHDA-279.48-ALC662.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/1236878/AppleHDA-279.48-ALC662.zip)

**Comment by insanelydeepak** [comment]
Hi 
i assumes you are not available now , so i'm closing this issue , feel free to reopen when  available
