### ISSUE TITLE
Laptop VIA VT1802 working sound output but not working built in mic

### ISSUE THREAD

**Issue by rosendolucas** [insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12#32]
Hello, before anything else I want to thank you all for your contribution to the people! it's really awesome!

I have a laptop build running Mac OS 10.13
Since I'm using Mac OS (first version I ran was Yosemite) I had not been. able to put mic to work with applehda nor cloverhda and it only worked using voodooHDA package

Now I have CloverHDA installer with Easy Kext Pro and the proper edits to my config.plist as you recommend in Via VT1802 files

I have been reading some other issues with other codecs and I see you recommend to try with code commander, the problem is that I don't know haw to do that and I can't find any guide to proceed

Thank a lot

Bye

![screen shot 2017-09-29 at 10 10 53](https://user-images.githubusercontent.com/32391667/31017632-86bb5062-a4ff-11e7-9f02-dfcaff6fa594.png)

[Archive.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/1344454/Archive.zip)

**Comment by insanelydeepak** [comment]
Hi 
please provide codec_dump
