### ISSUE TITLE
ALC256 No output/input devices detected

### ISSUE THREAD

**Issue by mayankbudhwani** [insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12#33]
[ProblemReport.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/1362152/ProblemReport.zip)
I have been trying and trying for the last few days to get audio working on my laptop but to no avail. Audio codec is ALC256. I tried ALC256-v2 thing but couldn't get audio to work. Problem Reporting files attached. Please help out if possible.

**Comment by insanelydeepak** [comment]
Hi 
can you provide codec dump ??
