### ISSUE TITLE
Dell optiplex 9020

### ISSUE THREAD

**Issue by MohamadHowar** [insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12#34]
Dear ,
I've installed Sierra 10.12.3 on my Desktop Dell 9020 but I'm facing a problem with drivers  Audio realtek ALC 3220 
.
I'm trying to find a way to solve this issue on YouTube and Google and can't every time Mac painc with error message  
I used mulibeast voodoo too not success 
Please Help if there is a way to fix this issue for sound card

**Comment by MohamadHowar** [comment]
I followed this steps and works perfect thank you https://youtu.be/YdjVqbA6pZ4

**Comment by insanelydeepak** [comment]
Great 
Enjoy good sound

**Comment by brousseau6933** [comment]
To MohamadHowar: would you mind sharing your config.plist patches and dummy HDA?

Thanks,

Patrice
