### ISSUE TITLE
cloverHDA do not work with ALC256

### ISSUE THREAD

**Issue by sdarktemplar** [insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12#35]
Hi,
there is no audio device after I install the  cloverHDA. IOReg, EFI folder, kext status as attachment. please help, Thanks!
[Archive.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/1424921/Archive.zip)

**Comment by insanelydeepak** [comment]
Hi
how you install CloverHDA ??

**Comment by sdarktemplar** [comment]
Hi, copy it to S/L/E and run
sudo chmod -Rf 755 /S*/L*/E*
      sudo chown -Rf 0:0 /S*/L*/E*
      sudo touch -f /S*/L*/E*
      sudo kextcache -Boot -U /

**Comment by insanelydeepak** [comment]
i check your files and it show no cloverHDA is not loaded  
do you have vanilla appleHDA ?

**Comment by sdarktemplar** [comment]
No, I don't, is it necessary?

**Comment by insanelydeepak** [comment]
yes , you must have vanilla AppleHDA , non patched 
get one from here 
https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/tree/master/Vanilla%20AppleHDA%20

**Comment by sdarktemplar** [comment]
how could I install them? I use the EasyKext pro or copy to S/L/E manually, the command  "sudo kextcache -Boot -U /" does not show the cloverHDA.kext or AppleHDA.kext are been loaded.

**Comment by sdarktemplar** [comment]
Yuis-MacBook-Pro:~ yui$ kextstat | grep -y AppleHDA 
   94    0 0xffffff7f82e94000 0x1d000    0x1d000    com.apple.driver.AppleHDAController (279.48) ED51F180-19C8-3DE1-AF81-0E389D98ADDE <93 92 79 12 7 6 5 4 3 1>

Does it be loaded? there is still no audio device

**Comment by insanelydeepak** [comment]
no 
send me your DSDT

**Comment by sdarktemplar** [comment]
I reinstall the system, and I do not use DSDT now, I give you my EFI
[Archive.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/1426288/Archive.zip)

**Comment by sdarktemplar** [comment]
Yuis-MacBook-Pro:DSL yui$ kextstat | grep -y AppleHDA
  104    1 0xffffff7f82631000 0x1d000    0x1d000    com.apple.driver.AppleHDAController (279.48) ED51F180-19C8-3DE1-AF81-0E389D98ADDE <103 102 77 12 7 6 5 4 3 1>
  119    0 0xffffff7f827b3000 0xb5000    0xb5000    com.apple.driver.AppleHDA (9276.26) 806B8C17-50CA-3C6B-90B3-195F38D8FB89 <118 104 103 102 97 77 6 5 4 3 1>
  122    0 0xffffff7f83112000 0x2000     0x2000     com.apple.driver.AppleHDAHardwareConfigDriver (279.48) 14690424-1048-3F1D-8A3D-41657C97EB67 <4 3>

Does it be loaded now?

**Comment by insanelydeepak** [comment]
yes 
whats result now ?

**Comment by sdarktemplar** [comment]
Mic work, I could use app to record voice, but could not play, no sound at speaker and headphone either.

and sometimes boot, there is no device, the kext as below
Yuis-MacBook-Pro:DSL yui$  kextstat | grep -y AppleHDA
   92    1 0xffffff7f82620000 0x1d000    0x1d000    com.apple.driver.AppleHDAController (279.48) ED51F180-19C8-3DE1-AF81-0E389D98ADDE <91 90 74 12 7 6 5 4 3 1>
  128    0 0xffffff7f827a2000 0xb5000    0xb5000    com.apple.driver.AppleHDA (9276.26) 806B8C17-50CA-3C6B-90B3-195F38D8FB89 <127 95 92 91 90 74 6 5 4 3 1>

**Comment by insanelydeepak** [comment]
OK 
i will look at your codec dump and try to help you

**Comment by sdarktemplar** [comment]
do I need FakePCIID_Intel_HDMI_Audio.kext?

**Comment by insanelydeepak** [comment]
no i don't think

**Comment by sdarktemplar** [comment]
Ok, thanks for your help

**Comment by sdarktemplar** [comment]
do I need CodecCommander.kext?

**Comment by insanelydeepak** [comment]
yes

**Comment by sdarktemplar** [comment]
Will you have a update?

**Comment by insanelydeepak** [comment]
it took time to process , i only do in my free time

**Comment by sdarktemplar** [comment]
OK, I will continue to try and waiting for your update.

**Comment by MuntashirAkon** [comment]
To get everything to work on ALC256, you MUST install SSDT-ALC256.aml at /Clover/ACPI/Patched and add it to config.plist/ACPI/SortedOrder and install CodecCommander.kext at /L/E

**Comment by insanelydeepak** [comment]
Hi 
im closing this issue for now , if still have any feel free to re-open it
