### ISSUE TITLE
Combo jack no mice 

### ISSUE THREAD

**Issue by bhandari45** [insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12#36]
hi'
Combo jack dosenot work after install  cloverHDA  sound on headphone and  speaker.
subwoffer is not working but that is ok.
CloverHDA on S/L/E , DSDT PATCH , kextopatch on config.plist, SSDT-ALC-2566.aml on ACPI/PATCHED.
I have attach EFI/CLOVER, IOREG, codec_dump.txt from linux, kextcache from terminal and kextstat | grep -y AppleHDA
help please
Thanks !!
[Archive.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/1464884/Archive.zip)

**Comment by insanelydeepak** [comment]
Hi 
 provide me codec_dump from linux

**Comment by bhandari45** [comment]
[codec_dump.txt](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/1527088/codec_dump.txt)
Here is the file

**Comment by insanelydeepak** [comment]
Hi 
im going to look are your issue ?  are you available let me know

**Comment by insanelydeepak** [comment]
Im closing for now , feel free re-open when  you available
