### ISSUE TITLE
ALC288 No sound at all

### ISSUE THREAD

**Issue by egore24** [insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12#37]
[untitled folder.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/1469555/untitled.folder.zip)

I have replaced the vanilla AppleHDA from 10.12.6 in 10.13.1 and installed your patches, but there is no sound at all. I have attached your requested troubleshooting files. Please help. Thanks much!

**Comment by insanelydeepak** [comment]
Hi 
@egore24  how are you 
appleHDA from 10.12.6 will not work in 10.13 
try this one for 10.13 

[AppleHDA-280.12-ALC288.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/1524489/AppleHDA-280.12-ALC288.zip)
