### ISSUE TITLE
ALC298 working headset, no sound on external speaker (laptop)

### ISSUE THREAD

**Issue by KireinaHoro** [insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12#38]
The attached archive contains the required information. 
[debug_4409.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/1592855/debug_4409.zip)

![image](https://user-images.githubusercontent.com/7804730/34433824-cbb226aa-ecbc-11e7-93ba-318b18a0a15c.png)

(There's no Intel High Definition Audio there, though; the screenshot says "Audio" under "Hardware")

Thanks in advance.

**Comment by KireinaHoro** [comment]
@insanelydeepak how's everything going?

**Comment by KireinaHoro** [comment]
Relevant commit: https://github.com/vit9696/AppleALC/commit/fa49e29696c042d4f323ce73802ef5661c13cb72#diff-2ae84bbcfa3f529bc93e0fa7f2e4e0a0

**Comment by insanelydeepak** [comment]
Hi 
can you explain your issue ?  so i can help better

**Comment by insanelydeepak** [comment]
Hi 
closing this assuming you are un available , feel free to re-open anytime
