### ISSUE TITLE
ALC298 Razer Blade (laptop), Internal Speaker/External Mic, No Signal

### ISSUE THREAD

**Issue by NinYagami** [insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12#39]
Hi,

I'm currently using the CloverHDA package for ALC298 on my Razer Blade, and it appears that _internal/external speakers_ and _internal/external mics_ are **detected**. However, there are still a few issues:

1. The _internal speaker_ **does not output audio** when the headphones are unplugged.

2. The _mic_ **does not switch from internal to external** when an external mic is plugged into the combo jack. Sound continues to be registered from the internal microphone.

Would you mind patching the ALC298 version for the Blade? I attached the requested troubleshooting files below. If any additional files are needed, please let me know.

Thanks in advance!

[ALC298BladeReport.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/1613447/ALC298BladeReport.zip)

**Comment by insanelydeepak** [comment]
Hi
can you post codecDump ?
did you install all files , CodecCommander  + ALCFix + SSDT298 ?

**Comment by insanelydeepak** [comment]
>  but I patched DSDT layout to be 13. "SSDT298" was not mentioned in the README or the ALC298.zip. Did I miss something by accident?

let it its not recommend for you

**Comment by insanelydeepak** [comment]
try this 10.13 
Layout 13

[AppleHDA-280.12-ALC298-Razer_Blade_.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/1654755/AppleHDA-280.12-ALC298-Razer_Blade_.zip)

**Comment by NinYagami** [comment]
I couldn't get that file to work.

In the meantime, I found one that sometimes works. It breaks (not work) on 1/3 reboots.
Here is the full report of when it does not work:

[AppleHDA 10.12.6 Layout 3 RB.kext.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/1654834/AppleHDA.10.12.6.Layout.3.RB.kext.zip)

[DSDT.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/1654833/DSDT.zip)

[RB - Broken Audio.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/1654835/RB.-.Broken.Audio.zip)

**Comment by insanelydeepak** [comment]
try this one 
this is for 10.12 

[AppleHDA-279.48-ALC298-Razer_Blade_.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/1654838/AppleHDA-279.48-ALC298-Razer_Blade_.zip)

**Comment by insanelydeepak** [comment]
use this DSDT 
[DSDT.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/1654847/DSDT.zip)

**Comment by NinYagami** [comment]
Working same as above. I used your AppleHDA 279.48 and DSDT. Audio randomly breaks on some reboots.

I attached a report for both working and broken reboots below.

Also, I noticed that when I leave my mic in the combo jack if I reboot with working audio, the system detects "Internal Mic". I need to pull and replug the mic to get "Line In". OSX bug and not driver bug?

[279.48 Broken Report.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/1654903/279.48.Broken.Report.zip)
[279.48 Working Report.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/1654904/279.48.Working.Report.zip)

**Comment by insanelydeepak** [comment]
report about this kext only AppleHDA-279.48-ALC298-Razer_Blade_.zip

Speakers : working or not ?
Headphone : working or not 
Mic Int = working or not ?
Mic Ext (line-in) = working or not ? 

take your reboot or sleep issue after it

**Comment by NinYagami** [comment]
Report about AppleHDA-279.48-ALC298-Razer_Blade_.zip:

Speakers: working
Headphone: working
Mic Int = working
Mic Ext (line-in) = working however! shows (Mic Int on boot until pull out and plug in Mic Ext again)

**Comment by insanelydeepak** [comment]
use codec commander

**Comment by NinYagami** [comment]
Changes: Put SSDT-298.aml in ACPI/patched. Already using CodecCommander (2.6.3).

Update: Report about AppleHDA-279.48-ALC298-Razer_Blade_.zip:

Speakers: working!
Headphone: working!
Mic Int = working!
Mic Ext (line-in) = working!

Issue audio still broken on reboot still there. Working on 4/6 reboots.

**Comment by insanelydeepak** [comment]
no don't use SSDT just codec_commander or try without codec commander

**Comment by insanelydeepak** [comment]
try this kext too , dont use it with codec_commander

[EAPDFix.kext.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/1655028/EAPDFix.kext.zip)

**Comment by NinYagami** [comment]
Is EAPDFix for the reboot problem?

When I use it I get Mic Ext problem again. Reason I need SSDT 298 is because CodecCommander Info.plist does not include 298 codec by default.

Report for EAPDFix, CodecCommander w/ and w/o SSDT
EAPDFix.kext = Mic Ext not detected
CodecCommander = Mic Ext not detected
CodecCommander with SSDT-298 = Mic Ext working

SSDT from here: https://bitbucket.org/RehabMan/os-x-eapd-codec-commander/src/f0fb1de4ea1e8a31331303e5993f2c005ab449d7/SSDT-ALC298.dsl?at=master&fileviewer=file-view-default

**Comment by insanelydeepak** [comment]
Great 

> CodecCommander with SSDT-298 = Mic Ext working

its working fine with Reboots too ?

**Comment by NinYagami** [comment]
Sorry, no. CodecCommander solves Mic Ext problem but not reboot problem. Last try worked 1/4 reboots. It's really random.

**Comment by insanelydeepak** [comment]
try this 

[alc_fix.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/1655106/alc_fix.zip)

**Comment by insanelydeepak** [comment]
Your codec added to Repository 
https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/blob/master/Laptop/ALC298_v3-Razor%20Blade.zip

**Comment by insanelydeepak** [comment]
> Could there be anything else that is causing the problem
not sure , can remove it see result

**Comment by NinYagami** [comment]
Working 2/4 reboots after removed alc_fix. I attached the report for when the audio is broken. Does it reveal anything?

[279.48 Broken Report 2.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/1655178/279.48.Broken.Report.2.zip)

**Comment by insanelydeepak** [comment]
this is strange 
do fresh OSX install OSX 
use Patched AppleHDA + Codec_commander + SSDT298 only

**Comment by NinYagami** [comment]
Sure, I'll reinstall OSX tonight. I'll have to report to you later because it's late.

Thanks for you help!

**Comment by insanelydeepak** [comment]
welcome 
GoodLuck 👍

**Comment by NinYagami** [comment]
I installed OSX Sierra with the minimum to get it booted with WiFi. 

I want to report but I don't have the bdmesg command. I feel like I should know what that is but I don't remember when I had it in the old installation. Do you happen to have a binary?

**Comment by insanelydeepak** [comment]
> I don't remember anything about this. Do you happen to have a binary?

you need to re-install clover , its a binary file need to install again

**Comment by NinYagami** [comment]
I re-installed clover and OSX on a separate partition "TestOS", but the truth is bdmesg works in the original installation on "MacOS" partition. It only has a problem in the new installation. I'm going to see if I can get support for this problem in the forum because I can't report without bdmesg working.

**Comment by NinYagami** [comment]
Fixed Clover issue, created report of clean 10.12.6 sound.
+ Audio seems to be working on 20/20 reboots
- Headphones distorted -> will install alc_fix
- Mic Ext no longer detected

When I plug in Mic Ext, Mic Int continues to be read.

[279.48 Clean Report.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/1660485/279.48.Clean.Report.zip)

**Comment by NinYagami** [comment]
And right after I posted that it is back to being random again. In all honesty I think maybe installing clover to the partition breaks it. I'm using Clover-r4359 with RC-scripts and CloverEFI 64-bits SATA.

[279.48 Clean Report, Broken.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/1660525/279.48.Clean.Report.Broken.zip)

**Comment by insanelydeepak** [comment]
>  I can't report without bdmesg working.

you dont need to care about bdmesg i dont need clover output 

> Audio seems to be working on 20/20 reboots

thats great

**Comment by insanelydeepak** [comment]
repo update 
enjoy good sound

**Comment by NinYagami** [comment]
Working on 45/50 reboots. Honestly I don't think hackintosh is ever 100%, so I'll consider it fixed.

Thanks InsanelyDeepak!

**Comment by insanelydeepak** [comment]
>  Honestly I don't think hackintosh is ever 100%, so I'll consider it fixed.

correct Hack is 99.99% never 100% so we always have to patch it 

Enjoy good sound :)
