### ISSUE TITLE
Internal Microphone not working on Asus Zenbook Pro UX501VW

### ISSUE THREAD

**Issue by FelixJuggler** [insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12#4]
Hi insanely Deepak,
I wanted to report an issue with my laptop after using the Clover HDA kext with HDA Enabler13 kext on Sierra. Audio is working fine but unfortunately the built-in microphone does not work (just by simply testing my voice with a voice recorder app or in Sys Pref/Sound/input). The device is shown in Sys Pref but not working.
The codec on the laptop is Realtek ALC668, listed in DPCI Manager as: Audio Device 0x8086A170, Sub Device 0x10431080, Codec ID 0x10EC0668
I attach my files as requested in troubleshooting, I would appreciate if you have spare time to look into it.
Thanks a lot!!

![intelhighdefaudio](https://cloud.githubusercontent.com/assets/22938322/19523629/b3308cae-95e0-11e6-821a-9ba44fcec01a.jpg)

[Chris’s MacBook Air.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/539332/Chris.s.MacBook.Air.zip)
[config.plist.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/539334/config.plist.zip)
[Kextstat.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/539339/Kextstat.zip)

**Comment by insanelydeepak** [comment]
did you tested laetst one with codec commander inside ?

**Comment by insanelydeepak** [comment]
this is exact version for you , try 
https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/blob/master/Laptop/ALC668.zip

**Comment by FelixJuggler** [comment]
Yes I used the codec commander inside the zip related to ALC668 in your repo, the exact version you linked. Installed with easy kext pro both kexts and rebuilt cache permissions with "sudo touch /System/Library/Extensions && sudo kextcache -u /". Audio is working without problems but the internal mic shows no input at all (I tested it with Siri and SysPref/Sound). I'm a bit confused, maybe the sub device ID is different and the hardware has differences even if the codec is the same?

**Comment by insanelydeepak** [comment]
can you post codec_dump ?

**Comment by FelixJuggler** [comment]
Yeah I will post it soon, I have to create a USB stick with linux because I don't have it on the PC.

**Comment by insanelydeepak** [comment]
> I have to create a USB stick with linux because I don't have it on the PC.

use Live USB

**Comment by FelixJuggler** [comment]
Yep just did that thanks! ok so I generated the codec dump in terminal with "cat /proc/asound/card0/codec#0 > ~/codec_dump.txt
Here's the file:
[codec_dump.txt](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/544828/codec_dump.txt)

**Comment by insanelydeepak** [comment]
try with or without codeccommander 
[ALC668.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/545615/ALC668.zip)

**Comment by FelixJuggler** [comment]
Ok tested but still no luck unfortunately:
Without codec commander: Devices not recognized and no audio
With codec commander: Devices recognized, working audio but still no microphone input.

I wonder what the problem is. For example, Before CloverHDA, I used Mirone HDA patcher and again I get audio but no microphone, then I looked into layout3.xml from his patch and changed the MuteGPI0 key from value 1342242840 to value 1342242841. The result was no audio output at all, but working microphone (tested with Siri and Syspref/sound). That's weird I cannot get both working.

**Comment by insanelydeepak** [comment]
this one 

[ALC668.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/545829/ALC668.zip)

I think you should wait until I'm done with it , what you say ?

**Comment by FelixJuggler** [comment]
Yeah sorry, I don't have background in this I just wanted to try being helpful. I'll test it right away

**Comment by insanelydeepak** [comment]
try this one  too 
[ALC668 v2.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/545833/ALC668.v2.zip)

**Comment by insanelydeepak** [comment]
> Yeah sorry, I don't have background in this I just wanted to try being helpful. I'll test it right away

hey no problem , this is really good 

> That's weird I cannot get both working.
I was saying about this , I did adjustment few days back for Asus Zenbook Pro

**Comment by FelixJuggler** [comment]
Ok tested the second ALC668.zip
Without codec commander: Devices recognized but no audio and no microphone
With codec commander: Devices recognized, audio working, but still no microphone input.
I'm going to test v2 now.

**Comment by FelixJuggler** [comment]
Tested ALC668 v2.zip
Without codec commander: Devices recognized but no audio and no microphone
With codec commander: In Output, built in Internal Speakers are recognized and audio is working, in input I can see only built-in internal speakers but no internal microphone entry under Name and no input is detected.

**Comment by insanelydeepak** [comment]
can you provide kext has working Mic ?

**Comment by insanelydeepak** [comment]
for instance try this 
[ALC668.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/545897/ALC668.zip)


you try with codec_commander latest version , archive contains old one

**Comment by FelixJuggler** [comment]
Ok I'll try right away, in the meantime this is Mirone's kext with working mic but audio not working, I also attach the config.plist that has the relative kext to patch from his app.
[aDummyHDA.kext.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/545975/aDummyHDA.kext.zip)
[config.plist.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/545978/config.plist.zip)

**Comment by FelixJuggler** [comment]
So for the last try I got:
v1,v2,v3,v8,v9 all show only internal speakers in Input devices and no microphone input
v4,v5,v6 all show internal microphone and internal speakers in Input devices but still no microphone input.
All the versions from v1 to v9 have working audio output but no microphone input.

**Comment by insanelydeepak** [comment]
> can you provide kext has working Mic ?

**Comment by FelixJuggler** [comment]
I tried to get the mic without audio working again but I could not! I'm really out of ideas...

**Comment by FelixJuggler** [comment]
Ok new observation: I have dual booting with windows 10, if I boot windows 10 first and then from there restart to boot the OS, I lose audio output. But in input the internal microphone seems to have signal (by looking at input level). If I try Siri to test it, I still don't get any response.

**Comment by FelixJuggler** [comment]
No problem I was aware of that, take all the time you need it doesn't seem an easy fix! Thanks!!

**Comment by insanelydeepak** [comment]
hello 
you need custom profile with codec commander for your system 
I have in repo wich is not working for you , also Codec commander has one profile for 668 , you have to override it while making yours

**Comment by FelixJuggler** [comment]
Yeah but how do I create a custom profile? I'm not really familiar with Codec commander. Do you have  any advice on how to do it?

**Comment by insanelydeepak** [comment]
Hi sorry I was kinda busy
its not a big deal , just REAME of Codec_commander

**Comment by insanelydeepak** [comment]
Hi 
are you available to debug ?

**Comment by insanelydeepak** [comment]
I assume you are not available to fix this issue 
for now I'm closing issue 
feel free to re-open issue 

Regards 
Deepak

**Comment by kprinssu** [comment]
I have the same laptop and I am willing to help out.

**Comment by insanelydeepak** [comment]
provide codec dump

**Comment by kprinssu** [comment]
https://gist.github.com/kprinssu/5632c204cbc1b16d54bf342c1b945842

**Comment by jonie87** [comment]
HI guys, i always want to install mac os on asus zenbokkpro ux501vw
can anyone send me amnuals for instalations??

please do it on my email: tadej.skafar@gmail.com

tnx guys

**Comment by kprinssu** [comment]
@jonie87 not the correct place to ask the question, go to tonymacx86.com. I am willing to help you if you manage to get macOS installed.

@insanelydeepak after some searching, I eventually created a SSDT for CodecCommander which fixes the microphone (see https://gist.github.com/kprinssu/26245208c3cc24b09a335b2e39e2f33e)

The headphone jack still has static but a minor problem for me at this point.
