### ISSUE TITLE
ALC256 Dell Latitude 7280

### ISSUE THREAD

**Issue by karterilla** [insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12#43]
[ALC256_Dell7280.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/1778565/ALC256_Dell7280.zip)
Hello I have installed cloverHDA following your steps, on this Dell laptop. Im'm running 10.13.3 updated today.
I can have device shown in Audio System Preferences,  but no audio from internal speaker neither from headphones jack.
CloverHDA in /S/L/E rebuilt rebuilt caches via kextcache -i /.
Cannot use Lilu otherwise my graphic panics, so I've choose your Clover method (by way thank you very much for what you are doing for the rest of us).
I've enclose Ioreg, efi config, Codec dump from Ubuntu, log (from which the only warning cloverHDA sports is invalid signature) and the rest of files you request for troubleshooting.

Thank you very much for your efforts for audio on hack.

**Comment by insanelydeepak** [comment]
Hi 
do you using any DSDT ? i was in files 
if not plz extract one use f4 while in cloverMenu and look in clover/APCI/Origin

**Comment by karterilla** [comment]
Hello.
[origin.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/1829122/origin.zip)

OK, this is the F4 dump. 

Thank you.

**Comment by insanelydeepak** [comment]
Hi 
i'm closing this issue , you need help and available feel free to re-open
