### ISSUE TITLE
Re-opening issue #13: Dell 9020 ALC280 all ins and outs

### ISSUE THREAD

**Issue by brousseau6933** [insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12#44]
Feel free to merge if it is not the right way to re-open an issue: https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/issues/13?_pjax=%23js-repo-pjax-container

I've just added a comment as I just want all the jacks working on my 9020. So far, I use tha AppleALC Lilu plugin and this way, I get the two front jacks working.

Here's my other comment on the closed issue:

"Reviving the thread as I'm a new 9020 owner. As you already know, the AppleALC lilu plugin gives only front input and output.

I've tried replacing my DSDT with the one in this thread. I removed the ALC plugin too and also put your kext in S/L/E.

With the latest one from june 17th: no sound at all. Here are my kextstat output, DSDT and config.plist: https://1drv.ms/u/s!AsCftN_jdRMFugPlwK1S3XkQTQ9Z

Thanks for your hard work.

Patrice"

**Comment by brousseau6933** [comment]
Kind of solved without CloverHDA:

Solved: all jacks working!

 Use AppleALC.kext lilu plugin and obviously Lilu.kext. Download the DSDT with Layout-ID 13 attached in the original #13 issue and that's it

**Comment by insanelydeepak** [comment]
Hi 
you should avoid AppleALC when using CloverHDA,
Both has same resource 

PS: i have own this laptop so, always relies upon user inputs to improve or bugfix , if you want to help in fixing it will be great

**Comment by brousseau6933** [comment]
Sorry, it's not a laptop. It's an Haswell desktop with two jacks on the front and two on the rear. I think the OP in the issue had the same computer but maybe it wasn't the same format: there is three, mini-tower, small form factor and ultra small form factor.

Thanks anyway. So, if I understand well, using CloverHDA with the same layout-id 13 should work?

**Comment by insanelydeepak** [comment]
yes

**Comment by brousseau6933** [comment]
Ok, so you could consider this issue closed then... Sorry!

**Comment by insanelydeepak** [comment]
Great
