### ISSUE TITLE
REALTEK 270 (ASUS K55VD)

### ISSUE THREAD

**Issue by enarce** [insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12#46]
PLEASE I NEED YOU HELP. I NOT HAVE AUDIO
[carpeta sin título.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/2046701/carpeta.sin.titulo.zip)

**Comment by insanelydeepak** [comment]
Hi 
i was away from while, if you still have issue let me know so we can fix it
