### ISSUE TITLE
alienware 15r3 headphone issue

### ISSUE THREAD

**Issue by Summer-Arrival** [insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12#47]
hi, thanks so much for what you are doing!
my laptop is Alienware 15 r3 my codec and pathmap are as same as this one here: https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/issues/16,
the only difference is my osx version is 10.13.4, and my cpu is skylake 6700hq, as the current cloverhda support 10.12 only, I have no idea how make my audio work,  have tried applealc with different layout id, customizing applealc, but headphone still not working, looking forward to hear your suggestion, thanks!
[platform-layout.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/2060200/platform-layout.zip)
[codec.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/2060201/codec.zip)

**Comment by insanelydeepak** [comment]
Hi 
i was away from while , if you still have issue let me know

**Comment by Summer-Arrival** [comment]
try to use this 10.13 version CloverHDA (https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/issues/21) you made for others with my own info, now the sound is normal, thanks for your work!

**Comment by insanelydeepak** [comment]
Great ! enjoy good sound 

i will make 10.13 and 10.14 soon so it'll be easy for many others to choose

**Comment by blackiceua** [comment]
@Summer-Arrival Can you provide your config.plist and EFI which you use for your laptop. I have the similar model: Alienware 17 R4 skylake 6700hq Intel 530/Nvidia 1060. But I can't enable sound.

**Comment by Summer-Arrival** [comment]
maybe you can try my cloverHDA, and follow the instruction at the bottom of issue #16, and don't forget add the layout id 13 to your config.list, that's all I did to make the sound work, good luck.
[cloverHDA.kext.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/2172308/cloverHDA.kext.zip)
