### ISSUE TITLE
ALC295 - Only Bottom Speakers Working

### ISSUE THREAD

**Issue by lolitsgab** [insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12#48]
[troubleshoot.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/2187108/troubleshoot.zip)

My machine is the[ HP Spectre X360 Kaby Lake 2017 model](https://support.hp.com/us-en/product/hp-spectre-13-ac000-x360-convertible-pc/14039877/manuals) dual-booting windows 10 and OS X 10.13.6

The issue is that only the secondary speakers that are located on the bottom of the computer work. The top (main) speakers (located on top of the keyboard)  do not work or output any sound. I have attached the IOREGExplorer output, my clover config file, my kextstat | grep -y AppleHDA output, and  a screen shot of the system profiler for my audio hardware.

I would be very thankful if you could help me out with this @insanelydeepak 

Thank you!

**Comment by insanelydeepak** [comment]
Hi 
this weekend i will take all issues your too

**Comment by lolitsgab** [comment]
Is there any more information that would be helpful in resolving the issue?

**Comment by insanelydeepak** [comment]
Hi 
sorry it took long time 

can you send me codec dump ??

**Comment by lolitsgab** [comment]
No problem. Here is a Codec Dump using Mirone's AppleHDA Patcher (jarvis)
[jarvis.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/2230465/jarvis.zip)

**Comment by lolitsgab** [comment]
[I have moved the issue to the appropriate section](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.13/issues/2). I will now close this issue. Thank you!
