### ISSUE TITLE
request for Lenovo ideapad 320-14ikb codec 10ec230

### ISSUE THREAD

**Issue by anmoolpk** [insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12#49]
I request to insanelydeepak   please patch applehda for me 
I attached codec dump which I extracted fro linux 
[CodecDump.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/2195760/CodecDump.zip)

**Comment by insanelydeepak** [comment]
Hi 
OSX Version ??

**Comment by insanelydeepak** [comment]
i will prefer 10.13 mojave is not good to trust 

will come with patch files

**Comment by anmoolpk** [comment]
Thanks sir i m waiting for your patch
Please make fast because i m runing high sierra without sound

**Comment by insanelydeepak** [comment]
Hi
install this and use Layout 13 

[AppleHDA-280.12-ALC230.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/2230751/AppleHDA-280.12-ALC230.zip)

**Comment by wandersonpassos** [comment]
Hi, I have the same laptop ... I tried all the ways, applealc, voodooHDA, and even tried patch myself appleHDA, layout ID 3, 13 and 20 worked but no audio in the speakers, only headphones and inputs work, I believe is something related to EAPD, must have some command to activate it, can anyone help me?

**Comment by insanelydeepak** [comment]
Hi 
i'm closing this repo , if you available please re-open it
