### ISSUE TITLE
ALC288 support

### ISSUE THREAD

**Issue by stealth658** [insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12#5]
Is there any chance we can get this working on the Dell XPS 13 9343's ALC288? Right now, the only option for this laptop is VoodooHDA, and while it works, it's not as ideal as a native solution. Thank you for your effort.

**Comment by insanelydeepak** [comment]
sure
 can you provide codec_dump ?

**Comment by stealth658** [comment]
Sure, here it is
[codec_dump.txt](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/544802/codec_dump.txt)

**Comment by insanelydeepak** [comment]
> Would you like the Intel HDMI codec dump as well?
no

**Comment by insanelydeepak** [comment]
try this Layout 13 

[ALC288.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/545623/ALC288.zip)

**Comment by stealth658** [comment]
![screen shot 2016-10-22 at 7 54 56 am](https://cloud.githubusercontent.com/assets/9551905/19619123/e4cff29c-982c-11e6-8c06-6b0706b1aece.png)
![screen shot 2016-10-22 at 7 55 16 am](https://cloud.githubusercontent.com/assets/9551905/19619124/ea52a642-982c-11e6-927b-46d8ef0d29be.png)
[kextstat.txt](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/545752/kextstat.txt)
[config.plist.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/545755/config.plist.zip)
[DSDT.dsl.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/545756/DSDT.dsl.zip)
Hey, thanks a lot for your help. So far, the Intel HDA is showing up in System Information, but no output/input devices in System Preferences > Sound. Also I've tried plugging in a headphones with mic, but that hasn't changed anything. And I've tried with and without CodecCommander

**Comment by insanelydeepak** [comment]
try this one 
make sure have vanilla AppleHDA 

[ALC288.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/545773/ALC288.zip)

**Comment by stealth658** [comment]
Yeah, I used your vanilla AppleHDA just in case. Okay so with the last one I've got the following (without codec commander):
Internal Speakers: show up in output but don't work
Headphones: show up when plugged in and work
Internal Microphone: shows up but doesn't work
External Microphone: doesn't show up when plugged in

**Comment by insanelydeepak** [comment]
this one 
[ALC288.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/545894/ALC288.zip)

**Comment by stealth658** [comment]
Link isn't working :\ 404

**Comment by insanelydeepak** [comment]
again here 
[ALC288.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/545896/ALC288.zip)

**Comment by stealth658** [comment]
Okay, so Headphones are still working, and the Internal Microphone is working now, but the Internal Speakers still show up but won't work. And External Microphone isn't detected when plugged in :\. Thank you so much for your effort. I really appreciate it. This is the closest I've gotten to native audio in a long time of trying.

**Comment by insanelydeepak** [comment]
this one 
[ALC288.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/545901/ALC288.zip)

> External Microphone isn't detected 

first we have to make speaker working

**Comment by stealth658** [comment]
Yeah external microphone is the least important. Should I try all of these? Maybe one will work?

**Comment by insanelydeepak** [comment]
> Should I try all of these? 
yeah Will be better , you can stop when found working one

**Comment by stealth658** [comment]
Hey, unfortunately, none of them seem to be working on my laptop. Some of them (3, 7, 8, 9) would just show no Internal Speaker in Output, and the rest would show it but sound wouldn't work :| Any ideas what I could try next?

**Comment by insanelydeepak** [comment]
use voodooHDA and provide voodooDump

**Comment by stealth658** [comment]
[voododump.txt](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/546439/voododump.txt)

**Comment by stealth658** [comment]
Is there anything there that might point us in the right direction?

**Comment by insanelydeepak** [comment]
is speaker works with Voodoo ?

**Comment by stealth658** [comment]
Yes, it works.

**Comment by insanelydeepak** [comment]
try this one 
[ALC288_v1.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/562443/ALC288_v1.zip)

**Comment by stealth658** [comment]
![screen shot 2016-10-31 at 1 36 01 pm](https://cloud.githubusercontent.com/assets/9551905/19864511/fafd4c4c-9f6e-11e6-90bd-5d9b46d8ab13.png)
This time, I'm getting nothing in System Information or System Preferences > Sound > Output/Input

**Comment by stealth658** [comment]
I did a fresh install with newly patched ACPI, and oddly enough, even the kexts you gave me that were partially working before aren't working at all any more :/ Any idea why that might be the case?

**Comment by stealth658** [comment]
So I did a fresh install of 10.12.2, and now, even the ones that were partially working before have nothing show up in System Preferences > Sound > Output/Input. Any idea why that might be the case?

**Comment by stealth658** [comment]
With your [kext](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/issues/5#issuecomment-255539743) on layout 13, I have working headphones with instant jack-sensing and internal microphone, and with AppleALC layout ID 3, I have working speakers/headphones (though jack-sensing takes a very long time) and no microphone. Any chance you can help me figure out what AppleALC is doing right?

**Comment by insanelydeepak** [comment]
Hi sorry I was kinda busy
if you want we can continue

**Comment by stealth658** [comment]
Hey, no problem. Yes, I'd love to. Is there anything I should provide for you?

**Comment by egore24** [comment]
I'll join in as I would like a better sound/mic/HDMI solution for the XPS9343. Where do we go next with this project? Thanks.

**Comment by egore24** [comment]
I have moved away from VoodooHDA and now have AppleALC in place (done on my own, I haven't tried any here yet) and internal speakers work just fine, headphone jack works, microphone does not. Microphone is shown in System report and appears as input in system preferences. Where to go from here?

**Comment by stealth658** [comment]
@egore24 I've noticed that with the AppleALC/Lilu kexts, my laptop slows down a lot. Almost unusable after a while. Wondering if you've had a similar experience. I'm back to using VoodooHDA for now :\

**Comment by egore24** [comment]
I haven't noticed any slow down between the two. Maybe another kext or remaining component conflicting from previous audio attempts? Did you completely remove Voodoo before trying AppleALC?

**Comment by insanelydeepak** [comment]
Hi 
was kinda busy , now available so we can continue

**Comment by stealth658** [comment]
Sure, where do you think we should begin?

**Comment by insanelydeepak** [comment]
yes I never has voodooHDA while with AppleHDA

**Comment by insanelydeepak** [comment]
I will provide AppleHDA , what OSX version you have ?

**Comment by stealth658** [comment]
I'm running Sierra 10.12.5. Thanks for your help!

**Comment by insanelydeepak** [comment]
try this Layout 13 

[AppleHDA-279.48-ALC288.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/1019237/AppleHDA-279.48-ALC288.zip)

**Comment by stealth658** [comment]
No go :(. No output/input devices in System Preferences. In System Information, just Internal Microphone and Speaker show up.

**Comment by insanelydeepak** [comment]
ok 
don't worry

**Comment by insanelydeepak** [comment]
this one 

[AppleHDA-279.48-ALC288.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/1019411/AppleHDA-279.48-ALC288.zip)

**Comment by stealth658** [comment]
Okay, so now we have some progress.

Internal Speakers: show up but doesn't work
Headphones: work fine
Internal Microphone: shows up but doesn't work

**Comment by insanelydeepak** [comment]
this one 
[ALC288.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/1019485/ALC288.zip)

**Comment by stealth658** [comment]
Okay, so I've given them all of a shot and this is what I've found:

v1: no jack-sensing, only mic works
v2-6: no jack-sensing, headphones and mic work

Also, these ones have no jack-sensing whereas the one you sent earlier automatically switches to headphones when they're plugged in.

**Comment by insanelydeepak** [comment]
yes I disable jack sense for now , will enable when got working every thing

**Comment by insanelydeepak** [comment]
speaker is not working ? 
which version has better output/inputs ?

**Comment by stealth658** [comment]
Yeah speaker has been the consistent issue. Better sound quality?

**Comment by insanelydeepak** [comment]
yes with all output and inputs too 

provide screenshot of sys preference - > device

**Comment by egore24** [comment]
I'd be happy to assist with this as well. What audio layout should be chosen for this codec on this machine? I can test what you have provided. Thanks!

**Comment by stealth658** [comment]
@egore24 it's layout ID 13. Looking forward to (hopefully) getting this working

**Comment by insanelydeepak** [comment]
always Layout_ID = 13 for my patches

**Comment by egore24** [comment]
The last upload with six options included, all have the same result:

Speakers (internal), Headphones and Microphone show up in Sys Prefs.

Working: Microphone on all
Not working: Speakers (internal) on all/Headphones on all

**Comment by insanelydeepak** [comment]
ok 
just use vodooHDA and send me dumps

**Comment by egore24** [comment]
[voodoo_dump.txt](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/1023121/voodoo_dump.txt)

**Comment by insanelydeepak** [comment]
Report plz 
what input and output works ?

**Comment by egore24** [comment]
With VoodooHDA, everything except HDMI Audio works.

Internal speakers, Headphones (and sensing), Microphone all work

**Comment by insanelydeepak** [comment]
I will look at report and make some progress

HDMI will also not work here you need to use Framebuffer patch for iGPU you have

**Comment by egore24** [comment]
Excellent, looking forward to what you come up with. Thanks!

**Comment by insanelydeepak** [comment]
@egore24 will you post your progress kext here , as per stealth658 said above ?

**Comment by egore24** [comment]
I'm not sure what you mean by progress kext. Sorry.

**Comment by insanelydeepak** [comment]
> I have moved away from VoodooHDA and now have AppleALC in place (done on my own, I haven't tried any here yet) and internal speakers work just fine, headphone jack works, internal microphone does not. Internal microphone is shown in System report and appears as input in system preferences. Where to go from here?

**Comment by egore24** [comment]
Oh, ok. Hmm, that's long gone. I can try to recreate it. I'll let you know what I come up with.

**Comment by insanelydeepak** [comment]
Thanks

**Comment by egore24** [comment]
[AppleHDA.kext.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/1023462/AppleHDA.kext.zip)

[Clover.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/1023468/Clover.zip)

[full Patched AppleHDA.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/1023471/full.Patched.AppleHDA.zip)

**Comment by egore24** [comment]
^^^Done with Mirone AppleHDA Patcher v1.8

Speakers work, but have "echoing" when an app is quit while playing audio. Microphone doesn't work.

**Comment by egore24** [comment]
Back to VoodooHDA for now.

**Comment by egore24** [comment]
Okay, thank you. Sleep well.

**Comment by insanelydeepak** [comment]
try this one 

[ALC288.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/1024495/ALC288.zip)

**Comment by stealth658** [comment]
Deepak you are the man! I just tried v3 at random, and Internal Speakers, Headphones, and Internal Microphone are all working!

I guess you've disabled jack-sensing, so maybe enabling that will fix it, but one thing is that when Internal Speakers are selected, sound comes from both Internal Speakers and Headphones if they are plugged in.

I'm about to head to bed, but I will try the rest tomorrow. I just wanted to thank you for your amazing effort and persistence.

**Comment by insanelydeepak** [comment]
v3 ? right ?
jack sense was disable let me enable it , first confirm its working

**Comment by insanelydeepak** [comment]
this one 
[ALC288.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/1024951/ALC288.zip)

**Comment by egore24** [comment]
Ok, I'm awake over here....

SUCCESS! It appears everything is working, internal speakers, headphone sensing and microphone with your latest upload. Excellent work! Thank you so much for your help.

Now to move onto enabling HDMI audio. I know you mentioned earlier a framebuffer patch will be needed. Any direction you could nudge me in to start to work on this component of audio for HD5500?

Thanks again!

**Comment by egore24** [comment]
One other thing, will the work we have done here remain persistent through future OS updates? If not, what will have to be done with the next update the breaks this? Thank you!

**Comment by insanelydeepak** [comment]
HDMI = > https://github.com/toleda/audio_CloverHDMI

dont worry about Future I will ask AppleALC developer to accept it in his repo , and I commit soon 

so you need to choose AppleALC or CloverHDA both are future proof

**Comment by egore24** [comment]
Excellent. Thank you for the link for HDMI. Do you think that solution will have a conflict with a display port output? This machine does not have an HDMI specific output connection.

Just so I'm understanding you correctly, once what we have done is accepted into the AppleALC repo, we then install that .kext instead? In doing so, leaving AppleHDA alone which can be freely updated with future OS updates.

**Comment by insanelydeepak** [comment]
`Do you think that solution will have a conflict with a display port output? This machine does not have an HDMI specific output connection.`

you need to apply patches as mentioned above , use clover method and HDMI will get detected in Output section 


`Just so I'm understanding you correctly, once what we have done is accepted into the AppleALC repo, we then install that .kext instead? In doing so, leaving AppleHDA alone which can be freely updated with future OS updates.`
you just need to use AppleALC and forgot about  Patched AppleHDA

**Comment by insanelydeepak** [comment]
try this version will be final 


[AppleHDA-279.48-ALC288.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/1025517/AppleHDA-279.48-ALC288.zip)

**Comment by egore24** [comment]
The final version works just fine! Thanks again.

**Comment by egore24** [comment]
I'd like to share this in the hackintosh thread for this machine, but do you think it would be better to wait until it is integrated into the AppleALC kext? If so, when can we know that this is part of the AppleALC kext?

**Comment by insanelydeepak** [comment]
No you don't have to wait for anything if AppleALC is not available still we have CloverHDA so no worries

**Comment by insanelydeepak** [comment]
you have same eps 9343 as @stealth658  has ?

**Comment by egore24** [comment]
I'm not sure if we have the exact same specifications, but mine is also an XPS 9343.

**Comment by stealth658** [comment]
I would prefer CloverHDA to be honest, I tried AppleALC + Lilu again
recently, and again my system became extremely laggy to the point where
it's unusable. I'm not sure what kext/DSDT issue is causing that, but it's
a problem I've consistently had.

**Comment by insanelydeepak** [comment]
https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/blob/master/Laptop/ALC288.zip

Here commit done
and im going to close this issue

**Comment by stealth658** [comment]
Thank you so much! There are some Microsoft Surface models that use the
ALC288, so hopefully it works for them as well.

**Comment by insanelydeepak** [comment]
Yes it should work 
but if it fails feel free to open issue or make new issue

**Comment by insanelydeepak** [comment]
here 
its added to AppleALC 
https://github.com/vit9696/AppleALC/commit/53ead4d9e328f9a2d41c112914a12a05dbd70132

@stealth658  you should give it a try again

**Comment by egore24** [comment]
Hmmm, just tried the CloverHDA and the Internal speakers are not working. Headphone sensing and the microphone work however.

**Comment by stealth658** [comment]
@egore24 can you please post your vanilla 10.12.5 AppleHDA kext here? I accidentally overwrote my backup when installing one of these kexts

**Comment by egore24** [comment]
Here you go:
[AppleHDA.kext.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/1025888/AppleHDA.kext.zip)

**Comment by egore24** [comment]
@stealth658 did you get CloverHDA to work with the internal speakers? I'm back to the patched AppleHDA and they are working again.

**Comment by insanelydeepak** [comment]
https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/tree/master/Vanilla%20AppleHDA%20

**Comment by insanelydeepak** [comment]
cloverHDA not working ?

**Comment by insanelydeepak** [comment]
did you tried AppleALC ??

**Comment by egore24** [comment]
I'll try AppleALC next.

**Comment by egore24** [comment]
I can't build AppleALC with xCode. Always getting errors.

Can you compile it to use?

**Comment by egore24** [comment]
CloverHDA does not have working speakers. Headphone and mic work though.

**Comment by insanelydeepak** [comment]
I think something messed , let me fix it

**Comment by insanelydeepak** [comment]
final version working fine for you ?

**Comment by egore24** [comment]
Yes, final version of AppleHDA works in all regards.

AppleALC won't build without errors and CloverHDA does not have working speakers.

**Comment by insanelydeepak** [comment]
AppleALC 
try in meanwhile
[AppleALC.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/1026471/AppleALC.zip)

**Comment by egore24** [comment]
That AppleALC is not there for download

**Comment by insanelydeepak** [comment]
This now 
[ALC288.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/1026544/ALC288.zip)

**Comment by insanelydeepak** [comment]
this too 
[AppleALC 2017-05-24 23-17-00.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/1026553/AppleALC.2017-05-24.23-17-00.zip)

**Comment by egore24** [comment]
Your latest "this too" is working just fine! Nice job and thank you again.

**Comment by insanelydeepak** [comment]
Both AppleALC and CloverHDA ??

**Comment by egore24** [comment]
Oops, that other upload was named ALC..didn't realize it was CloverHDA. I'll give that a try now...

**Comment by egore24** [comment]
Nope, CloverHDA still does not work through the speakers. 

Headphones and headphone sensing work as well as the microphone.

**Comment by egore24** [comment]
Internal speakers do show up as an option in system preferences, but there is no sound coming from the speakers.

**Comment by insanelydeepak** [comment]
I see 
AppleALC  or patched applehda or cloverhda has same files

**Comment by egore24** [comment]
Weird. 

I keep Audio device ID of 13 for all. CloverHDA is on it's own (without Lilu) with config file changes, AppleALC and Lilu with no config file changes. 

Does that sound correct?

**Comment by insanelydeepak** [comment]
yes layout 13 for all

**Comment by egore24** [comment]
Not sure what could be the issue then with CloverHDA...

**Comment by egore24** [comment]
Are we sure the config file kextstopatch are valid and accurate?

**Comment by insanelydeepak** [comment]
yes 
post your config.plist

**Comment by insanelydeepak** [comment]
This one 

[CloverHDA.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/1026684/CloverHDA.zip)

**Comment by egore24** [comment]
Essentials X'ed out:

[config.plist.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/1026685/config.plist.zip)

**Comment by egore24** [comment]
Still the same result with the latest CloverHDA. Internal speakers do not work but show up in system preferences, headphones and headphone sensing works as well as the microphone.

**Comment by insanelydeepak** [comment]
there's something issue , let it , enjoy good sound 

@stealth658 can you check cloverHDA

**Comment by egore24** [comment]
Thanks for everything. I'll go back to AppleALC for now. Hopefully sealth658 can help out. I'll keep checking here for progress. Nice job!

**Comment by stealth658** [comment]
Hey sorry, I had a really busy day. Just got to try out your CloverHDA kext. I have the same issue where the internal speakers do not work. Haven't tried AppleALC yet, but the patched AppleHDA.kext works great for me.

**Comment by stealth658** [comment]
The AppleALC kext you posted seems to be working fine (without the lag I experienced before). Thank you so much! This has made the experience much much better.

**Comment by insanelydeepak** [comment]
thats great 👍 


im trying to fix cloverHDA , plz help me to fix it up - just you need to test 
I will post later 
Thanks :)

**Comment by stealth658** [comment]
Sure. If there's anything else you need me to do, let me know. I've been trying to find a native audio solution for 2 years for this laptop, so I'm glad to do anything to help.

**Comment by insanelydeepak** [comment]
try this one 
[Clover.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/1027810/Clover.zip)

**Comment by egore24** [comment]
Should we use your latest upload with which kext?

**Comment by insanelydeepak** [comment]
save your AppleALC which can work from clover folder , now you need vanilla AppleHDA + cloverHDA (above post)
apply clover patches and done

**Comment by egore24** [comment]
Thought so. I'll be trying that now. Thanks.

**Comment by egore24** [comment]
And that did it! Nice job.

Now, after all of this is there a preferred method to use between the two? AppleALC or CloverHDA?

**Comment by insanelydeepak** [comment]
is it work ??

**Comment by egore24** [comment]
Yes. The dummy kext made CloverHDA work

**Comment by insanelydeepak** [comment]
cool 👍 
stay with AppleALC but if it fails , use CloverHDA going to commit

**Comment by egore24** [comment]
Excellent. Will do and thanks again!

**Comment by stealth658** [comment]
Just wanted to confirm that CloverHDA works for me as well now, but I'll follow your advice and use AppleALC. Thank you!

**Comment by insanelydeepak** [comment]
Cool 👍  
enjoy the good sound

**Comment by egore24** [comment]
Well, one more issue to resolve...Loss of sound after deep sleep. A restart brings it back.

**Comment by insanelydeepak** [comment]
> Well, one more issue to resolve...Loss of sound after deep sleep. A restart brings it back

fix is available 
http://forum.osxlatitude.com/index.php?/topic/3084-eapdjack-sense-fix-no-sound-and-jack-sense-issue-after-sleep/

.

**Comment by egore24** [comment]
Hello. I've been enjoying the native sound that we created here. There is a nagging issue of wide fluctuations in audio output volume. This occurs "on its own", without manual adjustment of the volume controls. Any idea how to address this issue? Thanks.

**Comment by insanelydeepak** [comment]
headphone or speaker ??

**Comment by egore24** [comment]
Speaker for sure. I'll check headphone.

**Comment by egore24** [comment]
Just the speakers. Headphones remain constant in volume.

**Comment by stealth658** [comment]
How can I replicate this? I haven't noticed any issue like the one you're
describing.

**Comment by egore24** [comment]
I'm simply listening to music. Nothing special.

**Comment by egore24** [comment]
Almost like there is a noise reduction thing going on between the speakers and microphone?

**Comment by egore24** [comment]
Further diagnosing... when the volume output has decreased, initiating a system sound (drag something to the trash, empty the trash. etc), the volume level is returned to where it should be, albeit for a short period of time. Very weird.

**Comment by insanelydeepak** [comment]
ok I will try to fix soon

**Comment by egore24** [comment]
Thank you

**Comment by egore24** [comment]
Repeatable. After triggering a system sound while playing another audio, the volume remains up where it should be for five seconds, then decreases on its own.

**Comment by stealth658** [comment]
I don't have this issue. I've listened to music/watched things without the volume level changing.

**Comment by egore24** [comment]
Everything else less card reader and HDMI audio working for you?

**Comment by stealth658** [comment]
The card reader also works (with experimental support) using Sinetek's driver [here](http://www.insanelymac.com/forum/topic/321080-sineteks-driver-for-realtek-rtsx-sdhc-card-readers/?p=2376387). But yeah everything else besides the DP audio is working.

**Comment by insanelydeepak** [comment]
try this 
make sure you remove cloverHDA or AppleALC before proceed

[test_288.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/1082322/test_288.zip)

**Comment by egore24** [comment]
Thanks for the effort, but both of those have the same behavior of fluctuating volume, reset to proper volume level by a system sound.

**Comment by insanelydeepak** [comment]
using Codec commander ?

**Comment by egore24** [comment]
Yes, I've tried all with and without Codec Commander

**Comment by egore24** [comment]
Additionally, I'm installing everything into S/L/E. Is that the preferred method?

**Comment by insanelydeepak** [comment]
yes

**Comment by egore24** [comment]
Ok, that's what I've been doing all along. Just thought that might have been an issue.

**Comment by stealth658** [comment]
@insanelydeepak I have this issue where when I reboot from Windows (or even shut down Windows and then boot into Sierra), my audio doesn't work. I know there's a way to fix it using CodecCommander.kext [(as seen here)](https://www.tonymacx86.com/threads/no-audio-after-reboot-from-windows-applehda-w-alc-668.187624/), but I'm not sure what I should set the values to.

**Comment by insanelydeepak** [comment]
simply install kext , you don't need custom commands to send

**Comment by insanelydeepak** [comment]
try this kext , remove codecCommander before using it 
[EAPDFix.kext.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/1087855/EAPDFix.kext.zip)

**Comment by stealth658** [comment]
The EAPDFix doesn't solve the issue of no sound after rebooting from Windows, unfortunately :|

**Comment by insanelydeepak** [comment]
@egore24 Can you try to use MIDI setup ??  for speaker

**Comment by insanelydeepak** [comment]
@stealth658 using AppleALC or AppleHDA ? send it

**Comment by egore24** [comment]
Thanks for the reply. I just tried all combinations with MIDI setup...with the same issue remaining. I plan on an OS reinstall and see if that does anything to help us here. Unless you have another idea? Thanks!

**Comment by insanelydeepak** [comment]
@egore24 did you try to change from 44 to 48 or 96 kHz ?? 
yes os re-intsall will be better

**Comment by insanelydeepak** [comment]
@stealth658  try this 

don't use EAPD with CC 

[288.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/1094508/288.zip)

**Comment by egore24** [comment]
Yes, I did try all of the kHz combinations. I'll re-install and report back.

**Comment by egore24** [comment]
Dang it. Issue persists even after OS X reinstall.

**Comment by insanelydeepak** [comment]
using ALC fix ? or CC ?

**Comment by egore24** [comment]
Not familiar with ALC fix. What/where is that? I have already tried CC with no luck.

**Comment by insanelydeepak** [comment]
try it 
[alc_fix.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/1098554/alc_fix.zip)

**Comment by egore24** [comment]
Tried it and it had no effect on the issue.

**Comment by insanelydeepak** [comment]
can you describe exact issue ?

**Comment by egore24** [comment]
Volume output decreases on its own, initiating a system sound (drag something to the trash, empty the trash. etc), the volume level is returned to where it should be, albeit for a short period of time. Very weird.

**Comment by egore24** [comment]
What's even more odd is VoodooHDA does not behave in this manner. The volume output remains where it should be.

**Comment by insanelydeepak** [comment]
post voodooDump

**Comment by egore24** [comment]
[VoodooDump.txt](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/1109709/VoodooDump.txt)
Here you go. Thanks.

**Comment by egore24** [comment]
[VoodooDump.txt](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/1113957/VoodooDump.txt)

Here it is. Thanks!

**Comment by insanelydeepak** [comment]
Hi I was quite busy 
I will look and revert you back 

Thanks for patience :)

**Comment by egore24** [comment]
Thanks for the update. In the meantime, I have completely wiped my drive, re-installed MacOS 10.12.6 and tried again with the same issues being present. So, I have once again returned to VoodooHDA. I'm wondering if there is a conflict with kext's somewhere or an issue in my config file. Maybe you have better direction on where to go from here. Thanks for all of your work on this!
