### ISSUE TITLE
request for ASUS VIVOBOOK X510UAR BQ414T codec CX8050

### ISSUE THREAD

**Issue by tctien342** [insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12#50]
Dear @insanelydeepak  !
Please help me with this codec bcs all the patch i found for this was have microphone and lineIn bug ! Cant get any signal while it still recognized !
Speaker and headphone is fine !
OS: 10.13 and 10.14
Report and codec dump: 
[AUDIO REPORT.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/2255962/AUDIO.REPORT.zip)

**Comment by tctien342** [comment]
Fixed by patching CodecCommander !!
[CodecCommander-CX8050.kext.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/2277599/CodecCommander-CX8050.kext.zip)

**Comment by insanelydeepak** [comment]
Great! enjoy a good sound 

this weekend is booked to fix all issue , you were in queue
