### ISSUE TITLE
Request for Asus UX430UA ALC295

### ISSUE THREAD

**Issue by gulios** [insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12#51]
Hi, 

Asus UX430UA
ALC295
Audio inject id: 3

I use Lilu+AppleALC and CodecCommander kexts and SSDT-ALC295.dsl with custom commands.
I have to run custom command "hda-verb 0x19 SET_PIN_WIDGET_CONTROL 0x20" because without that sound from headphones is distorted(crackling) and very quiet etc

The problem is when i reconnect headphones i'm losing sound from them. 
In Audio preferences i see output device changing so only "fix" is run "hda-verb 0x19 SET_PIN_WIDGET_CONTROL 0x20" again.
After wakeup sound is distorted again so one way to fix it is run the command...

For now i just set it in crontab every minute ;( 
Maybe you can create patch for that model?

[SSDT-UX430-KabyLake.aml.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/2284421/SSDT-UX430-KabyLake.aml.zip)

[codecALC295.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/2259288/codecALC295.zip)

**Comment by gulios** [comment]
ok, hieplpvip added ALC295 layout-id 12 for Asus UX430 but two things not working yet:
- no internal mic
- after sleep on headphones audio level is low. When i reconnect headphones it backs to normal volume

**Comment by insanelydeepak** [comment]
Hi 
did you try layout 13 ??

**Comment by gulios** [comment]
yes, i tried layout id 13 10min ago, and:
- no internal sound but see internal device
- headphones mic works
- sound from headphones after run hda-verb 0x19 SET_PIN_WIDGET_CONTROL 0x20 and after sleep volume is fine

so it looks that external mic is fixable but how ;(

**Comment by insanelydeepak** [comment]
yes it is 
do one thing download ALC298 from this repo and install alcfix ,

**Comment by insanelydeepak** [comment]
i will look at your code tomorrow 
i had lots 295 request but no one was able to help to release stable version 

i hope you can

**Comment by gulios** [comment]
Thank you!
btw, alcfix doesn't help 

![screenshot 2018-08-13 at 21 33 09](https://user-images.githubusercontent.com/14802005/44053668-a5142098-9f40-11e8-8fb8-728658c9efac.png)

**Comment by insanelydeepak** [comment]
Hi 
how you gonna test file 
cloverHDA or AppleHDA ?? 
if AppleHDA the what osx version you have ?

**Comment by gulios** [comment]
now i'm using AppleALC.kext and if it's not a problem i prefer it.
If not i can use cloverHDA (do not want to modify OS).
I'm using 10.14PB5 now

**Comment by insanelydeepak** [comment]
try this one 

[AppleALC.kext.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/2287842/AppleALC.kext.zip)

**Comment by insanelydeepak** [comment]
> If not i can use cloverHDA (do not want to modify OS).

this modify system at minimal level and used from very long time AppleALC doesn't exist

**Comment by gulios** [comment]
Layout 12 ? or 13 ?

**Comment by insanelydeepak** [comment]
13

**Comment by gulios** [comment]
ok, was very good:
- internal speakers works
- internal mic works
- headphones works
- headphone mic works
 until i reconnected headphones and lost audio in headphones at all but in speakers still works

**Comment by gulios** [comment]
i mean that i'm losing sound/audio from headphones when reconnect it.
Only way to back sound working in headphones is run hda-verb signal.

On screen you see that external mic and headphones sound back after i run command.
![screenshot 2018-08-14 at 19 25 06](https://user-images.githubusercontent.com/14802005/44107502-dfe820b8-9ff7-11e8-8bf0-f2f31628cbf7.png)

**Comment by insanelydeepak** [comment]
wait for solution now

**Comment by insanelydeepak** [comment]
install this 
[ALCPlugFix.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/2287942/ALCPlugFix.zip)

**Comment by gulios** [comment]
I see it works.
So you think this is only way to fix headphones switching ?
(add as daemon or loop script)

![screenshot 2018-08-14 at 19 34 50](https://user-images.githubusercontent.com/14802005/44107908-20b35ecc-9ff9-11e8-8646-122eb4e7d970.png)

**Comment by insanelydeepak** [comment]
> So you think this is only way to fix headphones switching ?

yes this is only way till

**Comment by insanelydeepak** [comment]
you must install this binary to get better result

**Comment by gulios** [comment]
ok, cool, i can live with that ;)
What exactly that binary does ? some hda-verb commands ?
And last question, will you add this ALC295.zip to your repo?

**Comment by insanelydeepak** [comment]
> What exactly that binary does ? some hda-verb commands ?
"hda-verb 0x19 SET_PIN_WIDGET_CONTROL 0x20" this only 

> will you add this ALC295.zip to your repo? 

in an hour 

binary code 
[ALCPlugFix-master.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/2287968/ALCPlugFix-master.zip)

**Comment by gulios** [comment]
cool, i've added launch daemon and now is great :)
Thank you !!!

**Comment by insanelydeepak** [comment]
https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/blob/master/Laptop/ALC295_v2%20Asus%20UX430UA.zip 

done posted here

**Comment by gulios** [comment]
great,
Thank you !!!

**Comment by gulios** [comment]
ok, i see that there is patch in plist, rebooting...

**Comment by gulios** [comment]
ok, it doesn't work with patches in config.plist
Have no idea...
With that kext it works 
[AppleALC-insanelydeepak.kext.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/2288251/AppleALC-insanelydeepak.kext.zip)

**Comment by hieplpvip** [comment]
@insanelydeepak Can you upload your patch for ALC295 to AppleALC repo? You can override my layout-id 12 patch, it's ok

**Comment by insanelydeepak** [comment]
> Can you upload your patch for ALC295 to AppleALC repo? You can override my layout-id 12 patch, it's ok

Hi i submitted files to vandroiy for AppleALC , see what he response 

till now enjoy mine version posted above

**Comment by insanelydeepak** [comment]
> AppleALC.kext - from official repo

AppleALC not supporting my files from yesterday , i made request to AppleALC developer to add this wait and watch , i'll post update 

till now enjoy mine version posted above

**Comment by insanelydeepak** [comment]
Hi guys 
https://github.com/acidanthera/AppleALC/commit/831fd7c3647c94b3d8a6739fdb0a0d89275d5ca0 
please test layout 14 for Asus 
and also try layout 15 to be sure files are good

**Comment by gulios** [comment]
Hi, 

14 - speakers + internal mic works great. Headphones + external mic works great (headphones with ALCPlugFix but it's fine as daemon) 

15 - no sound from speakers but see internal device. Internal mic works. Headphones + ext mic works with ALCPlugFix.

so 14 + ALCPlugFix it's great form me ;)

Thank you !

**Comment by gulios** [comment]
Checked again your AppleALC version + inject id 13
[AppleALC-insanelydeepak-13.kext.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/2303443/AppleALC-insanelydeepak-13.kext.zip)

and "mute" doesn't work too.

**Comment by insanelydeepak** [comment]
mute is not working in both mine above and AppleALC Default one ? right

**Comment by gulios** [comment]
right

**Comment by insanelydeepak** [comment]
i will work on this too , this weekend

**Comment by gulios** [comment]
ok, checked id 12 by @hieplpvip and "mute" works fine.

No rush, thx

**Comment by gulios** [comment]
ok, i spent a little time and "fixed" mute.

https://github.com/acidanthera/AppleALC/pull/310

Thanks @insanelydeepak  and @hieplpvip for your help !!!

**Comment by gulios** [comment]
ok, vandroiy2013 closed PR because of duplicated ALC295.
Can you merge my changes and remove 12/14/ layout id or merge it into one working ?
For me it doesn't matter which one but your changes + my little mute fix do the job on id 16 
https://github.com/acidanthera/AppleALC/pull/310/commits/28f3c7fa0209f5a711dd0bee451b545caa71d0e4

Thank you !

**Comment by insanelydeepak** [comment]
can you brief what exactly changes you made ? will be time saver for me, i don't have hardware to test

**Comment by gulios** [comment]
sure, i just:
- copied layout14.xml to layout16.xml
- created Platforms16.xml based on Platforms12.xml
there were 
<key>PathMapID</key>
 			<integer>295</integer>
you had "2" value.
After that "mute"started working.

Here all changes 
https://github.com/acidanthera/AppleALC/commit/28f3c7fa0209f5a711dd0bee451b545caa71d0e4

**Comment by insanelydeepak** [comment]
try this one layout 14 

[AppleALC Test Insanelydeepak.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/2306060/AppleALC.Test.Insanelydeepak.zip)

**Comment by gulios** [comment]
ok, it looks fine:
- internal speakers work
- internal mic works
- headphones works
- ext mic works
- mute works
Thank you

**Comment by insanelydeepak** [comment]
Great 
i will request vandroiy for update 

enjoy good sound

**Comment by insanelydeepak** [comment]
test this one please 
https://github.com/acidanthera/AppleALC/commit/3c30bfe7c223ae3e0c55cc594ae5f3a345201f91

**Comment by gulios** [comment]
ok, it works fine.

Thank you.

**Comment by insanelydeepak** [comment]
Great 

closing issue now 
enjoy good sound
