### ISSUE TITLE
Internal Microphone not working on HP Envy DV7 - 7203ss

### ISSUE THREAD

**Issue by jefernandez** [insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12#6]
Hi, 
Audio output works perfectly in my HP Envy DV7 7203ss with IDT92HD91BXX but input doesn't.

I attach the files.

[Archive.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/621290/Archive.zip)

[codec_dump3.txt](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/623931/codec_dump3.txt)
[codec_dump0.txt](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/623932/codec_dump0.txt)

![screen shot 2016-11-26 at 22 12 40](https://cloud.githubusercontent.com/assets/4927838/20643915/a056f6b4-b425-11e6-8ff4-a0cf67d7a044.png)

Could you help me with this problem?

Thanks a lot.

**Comment by insanelydeepak** [comment]
Hi sorry I was kinda busy
if you want we can continue

**Comment by jefernandez** [comment]
Yes, please.
I'd love to.

**Comment by insanelydeepak** [comment]
Hi 
should we start again ?

**Comment by insanelydeepak** [comment]
I assume you are not available to fix this issue 
for now I'm closing issue 
feel free to re-open issue 

Regards 
Deepak

**Comment by jefernandez** [comment]
Hello,

Sorry, I have just read the message. Could we continue with the issue?
