### ISSUE TITLE
ALC282 (id_80868C20) not working

### ISSUE THREAD

**Issue by jvloendersloot** [insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12#7]
My Acer has an ALC282 sound device with id: 80868C20 and it's not working.
(At least from what I could find it's an ALC282).

I followed your guide:
Installed ALC282.kext to /S/L/E 
I used clover for ID:13
And added the patches to clover.

I have attached all the files you requested.
[ALC282_80868C20.zip](https://github.com/insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12/files/654711/ALC282_80868C20.zip)

**Comment by insanelydeepak** [comment]
Hi sorry I was kinda busy
if you want we can continue

**Comment by jvloendersloot** [comment]
Yes please. What do you need?

**Comment by jvloendersloot** [comment]
I still want to continue.

**Comment by insanelydeepak** [comment]
Hi 
it shows thats CloverHDA not loaded , did you rebuild caches after install ?

plz provide codec_dump

**Comment by amallia** [comment]
Added. Thanks

**Comment by insanelydeepak** [comment]
Hi 
I assume you are not available now 
feel free to re-open it 

Thanks
