### ISSUE TITLE
How to make HDMI audio work? ALC256 on Dell 7559

### ISSUE THREAD

**Issue by dodvip123** [insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12#8]
I can't figure out how to make it work, my internal mic and speakers work fine with the ALC256 v2 kext

**Comment by insanelydeepak** [comment]
HDMI requires frame buffer edit as well DSDT edits, there are too many tutorials and patches are you can use them in order to get it HDMI working 
you can use AppleALC which has HDMI support and my layout inBuilt 
PS: I'm closing this issue
