### ISSUE TITLE
ALC255 not working 

### ISSUE THREAD

**Issue by ghost** [insanelydeepak/cloverHDA-for-Mac-OS-Sierra-10.12#9]
I have tested with both cloverHDA variants for ALC255. Also with layout id injection via DSDT patch and clover configs. I have no idea whats going on. kextscache says that cloverHDA is loaded correctly.
Please help. Thanks

**Comment by insanelydeepak** [comment]
Hi sorry I was kinda busy
if you want we can continue

**Comment by sherm4n90** [comment]
Hi @insanelydeepak, sorry for my mistake. I was using an AppleHDA.kext from a different macOS version. I got it working finally. Thanks, you can close the issue.
